version: '3'

tasks:
  gen:proto:
    cmds:
      - buf generate
      - buf export . --output build/proto
      - protoc --proto_path=build/proto --include_imports --include_source_info --descriptor_set_out=build/descriptors.pb $(find build/proto -name "*.proto")
      - rm -rf build/proto

  build: go build -v ./...

  test: go test -v ./...
