version: '3'

tasks:
  gen:proto:
    cmds:
      - rm -rf brij
      - rm -rf build
      - rm -rf brij_protos_dart/lib/gen && mkdir -p brij_protos_dart/lib/gen
      - rm -rf brij_protos_js/gen && mkdir -p brij_protos_js/gen
      - buf generate

  build: go build -v ./...

  test: go test -v ./...
