// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: brij/storage/v1/wallet/service.proto

package wallet

import (
	common "go.brij.fi/protos/brij/storage/v1/common"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPartnerInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPartnerInfoRequest) Reset() {
	*x = GetPartnerInfoRequest{}
	mi := &file_brij_storage_v1_wallet_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPartnerInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPartnerInfoRequest) ProtoMessage() {}

func (x *GetPartnerInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_brij_storage_v1_wallet_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPartnerInfoRequest.ProtoReflect.Descriptor instead.
func (*GetPartnerInfoRequest) Descriptor() ([]byte, []int) {
	return file_brij_storage_v1_wallet_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetPartnerInfoRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetPartnerInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	PublicKey     string                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	PrivacyUrl    string                 `protobuf:"bytes,3,opt,name=privacy_url,json=privacyUrl,proto3" json:"privacy_url,omitempty"`
	TermsUrl      string                 `protobuf:"bytes,4,opt,name=terms_url,json=termsUrl,proto3" json:"terms_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPartnerInfoResponse) Reset() {
	*x = GetPartnerInfoResponse{}
	mi := &file_brij_storage_v1_wallet_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPartnerInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPartnerInfoResponse) ProtoMessage() {}

func (x *GetPartnerInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_brij_storage_v1_wallet_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPartnerInfoResponse.ProtoReflect.Descriptor instead.
func (*GetPartnerInfoResponse) Descriptor() ([]byte, []int) {
	return file_brij_storage_v1_wallet_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetPartnerInfoResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetPartnerInfoResponse) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *GetPartnerInfoResponse) GetPrivacyUrl() string {
	if x != nil {
		return x.PrivacyUrl
	}
	return ""
}

func (x *GetPartnerInfoResponse) GetTermsUrl() string {
	if x != nil {
		return x.TermsUrl
	}
	return ""
}

type InitStorageRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	WalletAddress        string                 `protobuf:"bytes,1,opt,name=wallet_address,json=walletAddress,proto3" json:"wallet_address,omitempty"`
	Message              string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	EncryptedSecretKey   string                 `protobuf:"bytes,3,opt,name=encrypted_secret_key,json=encryptedSecretKey,proto3" json:"encrypted_secret_key,omitempty"`
	WalletProofSignature string                 `protobuf:"bytes,4,opt,name=wallet_proof_signature,json=walletProofSignature,proto3" json:"wallet_proof_signature,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *InitStorageRequest) Reset() {
	*x = InitStorageRequest{}
	mi := &file_brij_storage_v1_wallet_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitStorageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitStorageRequest) ProtoMessage() {}

func (x *InitStorageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_brij_storage_v1_wallet_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitStorageRequest.ProtoReflect.Descriptor instead.
func (*InitStorageRequest) Descriptor() ([]byte, []int) {
	return file_brij_storage_v1_wallet_service_proto_rawDescGZIP(), []int{2}
}

func (x *InitStorageRequest) GetWalletAddress() string {
	if x != nil {
		return x.WalletAddress
	}
	return ""
}

func (x *InitStorageRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *InitStorageRequest) GetEncryptedSecretKey() string {
	if x != nil {
		return x.EncryptedSecretKey
	}
	return ""
}

func (x *InitStorageRequest) GetWalletProofSignature() string {
	if x != nil {
		return x.WalletProofSignature
	}
	return ""
}

type InitStorageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitStorageResponse) Reset() {
	*x = InitStorageResponse{}
	mi := &file_brij_storage_v1_wallet_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitStorageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitStorageResponse) ProtoMessage() {}

func (x *InitStorageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_brij_storage_v1_wallet_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitStorageResponse.ProtoReflect.Descriptor instead.
func (*InitStorageResponse) Descriptor() ([]byte, []int) {
	return file_brij_storage_v1_wallet_service_proto_rawDescGZIP(), []int{3}
}

type GetInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicKey     string                 `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	WalletAddress string                 `protobuf:"bytes,2,opt,name=wallet_address,json=walletAddress,proto3" json:"wallet_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInfoRequest) Reset() {
	*x = GetInfoRequest{}
	mi := &file_brij_storage_v1_wallet_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoRequest) ProtoMessage() {}

func (x *GetInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_brij_storage_v1_wallet_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoRequest.ProtoReflect.Descriptor instead.
func (*GetInfoRequest) Descriptor() ([]byte, []int) {
	return file_brij_storage_v1_wallet_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetInfoRequest) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *GetInfoRequest) GetWalletAddress() string {
	if x != nil {
		return x.WalletAddress
	}
	return ""
}

type GetInfoResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	EncryptedSecretKey string                 `protobuf:"bytes,1,opt,name=encrypted_secret_key,json=encryptedSecretKey,proto3" json:"encrypted_secret_key,omitempty"`
	Message            string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	PublicKey          string                 `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	WalletAddress      string                 `protobuf:"bytes,4,opt,name=wallet_address,json=walletAddress,proto3" json:"wallet_address,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetInfoResponse) Reset() {
	*x = GetInfoResponse{}
	mi := &file_brij_storage_v1_wallet_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoResponse) ProtoMessage() {}

func (x *GetInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_brij_storage_v1_wallet_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoResponse.ProtoReflect.Descriptor instead.
func (*GetInfoResponse) Descriptor() ([]byte, []int) {
	return file_brij_storage_v1_wallet_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetInfoResponse) GetEncryptedSecretKey() string {
	if x != nil {
		return x.EncryptedSecretKey
	}
	return ""
}

func (x *GetInfoResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetInfoResponse) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *GetInfoResponse) GetWalletAddress() string {
	if x != nil {
		return x.WalletAddress
	}
	return ""
}

type GetSeedMessageRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	WalletAddress        string                 `protobuf:"bytes,1,opt,name=wallet_address,json=walletAddress,proto3" json:"wallet_address,omitempty"`
	WalletProofSignature string                 `protobuf:"bytes,2,opt,name=wallet_proof_signature,json=walletProofSignature,proto3" json:"wallet_proof_signature,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GetSeedMessageRequest) Reset() {
	*x = GetSeedMessageRequest{}
	mi := &file_brij_storage_v1_wallet_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSeedMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSeedMessageRequest) ProtoMessage() {}

func (x *GetSeedMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_brij_storage_v1_wallet_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSeedMessageRequest.ProtoReflect.Descriptor instead.
func (*GetSeedMessageRequest) Descriptor() ([]byte, []int) {
	return file_brij_storage_v1_wallet_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetSeedMessageRequest) GetWalletAddress() string {
	if x != nil {
		return x.WalletAddress
	}
	return ""
}

func (x *GetSeedMessageRequest) GetWalletProofSignature() string {
	if x != nil {
		return x.WalletProofSignature
	}
	return ""
}

type GetSeedMessageResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Message            string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	EncryptedSecretKey string                 `protobuf:"bytes,2,opt,name=encrypted_secret_key,json=encryptedSecretKey,proto3" json:"encrypted_secret_key,omitempty"`
	PublicKey          string                 `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetSeedMessageResponse) Reset() {
	*x = GetSeedMessageResponse{}
	mi := &file_brij_storage_v1_wallet_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSeedMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSeedMessageResponse) ProtoMessage() {}

func (x *GetSeedMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_brij_storage_v1_wallet_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSeedMessageResponse.ProtoReflect.Descriptor instead.
func (*GetSeedMessageResponse) Descriptor() ([]byte, []int) {
	return file_brij_storage_v1_wallet_service_proto_rawDescGZIP(), []int{7}
}

func (x *GetSeedMessageResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetSeedMessageResponse) GetEncryptedSecretKey() string {
	if x != nil {
		return x.EncryptedSecretKey
	}
	return ""
}

func (x *GetSeedMessageResponse) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

type GrantAccessRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	PartnerPublicKey   string                 `protobuf:"bytes,1,opt,name=partner_public_key,json=partnerPublicKey,proto3" json:"partner_public_key,omitempty"`
	EncryptedSecretKey string                 `protobuf:"bytes,2,opt,name=encrypted_secret_key,json=encryptedSecretKey,proto3" json:"encrypted_secret_key,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GrantAccessRequest) Reset() {
	*x = GrantAccessRequest{}
	mi := &file_brij_storage_v1_wallet_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrantAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrantAccessRequest) ProtoMessage() {}

func (x *GrantAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_brij_storage_v1_wallet_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrantAccessRequest.ProtoReflect.Descriptor instead.
func (*GrantAccessRequest) Descriptor() ([]byte, []int) {
	return file_brij_storage_v1_wallet_service_proto_rawDescGZIP(), []int{8}
}

func (x *GrantAccessRequest) GetPartnerPublicKey() string {
	if x != nil {
		return x.PartnerPublicKey
	}
	return ""
}

func (x *GrantAccessRequest) GetEncryptedSecretKey() string {
	if x != nil {
		return x.EncryptedSecretKey
	}
	return ""
}

type GrantAccessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrantAccessResponse) Reset() {
	*x = GrantAccessResponse{}
	mi := &file_brij_storage_v1_wallet_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrantAccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrantAccessResponse) ProtoMessage() {}

func (x *GrantAccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_brij_storage_v1_wallet_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrantAccessResponse.ProtoReflect.Descriptor instead.
func (*GrantAccessResponse) Descriptor() ([]byte, []int) {
	return file_brij_storage_v1_wallet_service_proto_rawDescGZIP(), []int{9}
}

type RevokeAccessRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PartnerPublicKey string                 `protobuf:"bytes,1,opt,name=partner_public_key,json=partnerPublicKey,proto3" json:"partner_public_key,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RevokeAccessRequest) Reset() {
	*x = RevokeAccessRequest{}
	mi := &file_brij_storage_v1_wallet_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeAccessRequest) ProtoMessage() {}

func (x *RevokeAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_brij_storage_v1_wallet_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeAccessRequest.ProtoReflect.Descriptor instead.
func (*RevokeAccessRequest) Descriptor() ([]byte, []int) {
	return file_brij_storage_v1_wallet_service_proto_rawDescGZIP(), []int{10}
}

func (x *RevokeAccessRequest) GetPartnerPublicKey() string {
	if x != nil {
		return x.PartnerPublicKey
	}
	return ""
}

type RevokeAccessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeAccessResponse) Reset() {
	*x = RevokeAccessResponse{}
	mi := &file_brij_storage_v1_wallet_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeAccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeAccessResponse) ProtoMessage() {}

func (x *RevokeAccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_brij_storage_v1_wallet_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeAccessResponse.ProtoReflect.Descriptor instead.
func (*RevokeAccessResponse) Descriptor() ([]byte, []int) {
	return file_brij_storage_v1_wallet_service_proto_rawDescGZIP(), []int{11}
}

type RemoveAllUserDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveAllUserDataRequest) Reset() {
	*x = RemoveAllUserDataRequest{}
	mi := &file_brij_storage_v1_wallet_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveAllUserDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveAllUserDataRequest) ProtoMessage() {}

func (x *RemoveAllUserDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_brij_storage_v1_wallet_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveAllUserDataRequest.ProtoReflect.Descriptor instead.
func (*RemoveAllUserDataRequest) Descriptor() ([]byte, []int) {
	return file_brij_storage_v1_wallet_service_proto_rawDescGZIP(), []int{12}
}

type RemoveAllUserDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveAllUserDataResponse) Reset() {
	*x = RemoveAllUserDataResponse{}
	mi := &file_brij_storage_v1_wallet_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveAllUserDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveAllUserDataResponse) ProtoMessage() {}

func (x *RemoveAllUserDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_brij_storage_v1_wallet_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveAllUserDataResponse.ProtoReflect.Descriptor instead.
func (*RemoveAllUserDataResponse) Descriptor() ([]byte, []int) {
	return file_brij_storage_v1_wallet_service_proto_rawDescGZIP(), []int{13}
}

type GetGrantedAccessPartnersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGrantedAccessPartnersRequest) Reset() {
	*x = GetGrantedAccessPartnersRequest{}
	mi := &file_brij_storage_v1_wallet_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGrantedAccessPartnersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGrantedAccessPartnersRequest) ProtoMessage() {}

func (x *GetGrantedAccessPartnersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_brij_storage_v1_wallet_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGrantedAccessPartnersRequest.ProtoReflect.Descriptor instead.
func (*GetGrantedAccessPartnersRequest) Descriptor() ([]byte, []int) {
	return file_brij_storage_v1_wallet_service_proto_rawDescGZIP(), []int{14}
}

type GetGrantedAccessPartnersResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Partners      []*GetPartnerInfoResponse `protobuf:"bytes,1,rep,name=partners,proto3" json:"partners,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGrantedAccessPartnersResponse) Reset() {
	*x = GetGrantedAccessPartnersResponse{}
	mi := &file_brij_storage_v1_wallet_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGrantedAccessPartnersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGrantedAccessPartnersResponse) ProtoMessage() {}

func (x *GetGrantedAccessPartnersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_brij_storage_v1_wallet_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGrantedAccessPartnersResponse.ProtoReflect.Descriptor instead.
func (*GetGrantedAccessPartnersResponse) Descriptor() ([]byte, []int) {
	return file_brij_storage_v1_wallet_service_proto_rawDescGZIP(), []int{15}
}

func (x *GetGrantedAccessPartnersResponse) GetPartners() []*GetPartnerInfoResponse {
	if x != nil {
		return x.Partners
	}
	return nil
}

type SetUserDataRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Type           common.DataType        `protobuf:"varint,1,opt,name=type,proto3,enum=brij.storage.v1.common.DataType" json:"type,omitempty"`
	EncryptedValue []byte                 `protobuf:"bytes,2,opt,name=encrypted_value,json=encryptedValue,proto3" json:"encrypted_value,omitempty"`
	Hash           string                 `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	Signature      string                 `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SetUserDataRequest) Reset() {
	*x = SetUserDataRequest{}
	mi := &file_brij_storage_v1_wallet_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetUserDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUserDataRequest) ProtoMessage() {}

func (x *SetUserDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_brij_storage_v1_wallet_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUserDataRequest.ProtoReflect.Descriptor instead.
func (*SetUserDataRequest) Descriptor() ([]byte, []int) {
	return file_brij_storage_v1_wallet_service_proto_rawDescGZIP(), []int{16}
}

func (x *SetUserDataRequest) GetType() common.DataType {
	if x != nil {
		return x.Type
	}
	return common.DataType(0)
}

func (x *SetUserDataRequest) GetEncryptedValue() []byte {
	if x != nil {
		return x.EncryptedValue
	}
	return nil
}

func (x *SetUserDataRequest) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *SetUserDataRequest) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

type SetUserDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetUserDataResponse) Reset() {
	*x = SetUserDataResponse{}
	mi := &file_brij_storage_v1_wallet_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetUserDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUserDataResponse) ProtoMessage() {}

func (x *SetUserDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_brij_storage_v1_wallet_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUserDataResponse.ProtoReflect.Descriptor instead.
func (*SetUserDataResponse) Descriptor() ([]byte, []int) {
	return file_brij_storage_v1_wallet_service_proto_rawDescGZIP(), []int{17}
}

type RemoveUserDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveUserDataRequest) Reset() {
	*x = RemoveUserDataRequest{}
	mi := &file_brij_storage_v1_wallet_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveUserDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveUserDataRequest) ProtoMessage() {}

func (x *RemoveUserDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_brij_storage_v1_wallet_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveUserDataRequest.ProtoReflect.Descriptor instead.
func (*RemoveUserDataRequest) Descriptor() ([]byte, []int) {
	return file_brij_storage_v1_wallet_service_proto_rawDescGZIP(), []int{18}
}

func (x *RemoveUserDataRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RemoveUserDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveUserDataResponse) Reset() {
	*x = RemoveUserDataResponse{}
	mi := &file_brij_storage_v1_wallet_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveUserDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveUserDataResponse) ProtoMessage() {}

func (x *RemoveUserDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_brij_storage_v1_wallet_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveUserDataResponse.ProtoReflect.Descriptor instead.
func (*RemoveUserDataResponse) Descriptor() ([]byte, []int) {
	return file_brij_storage_v1_wallet_service_proto_rawDescGZIP(), []int{19}
}

type GetUserDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IncludeValues bool                   `protobuf:"varint,1,opt,name=include_values,json=includeValues,proto3" json:"include_values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserDataRequest) Reset() {
	*x = GetUserDataRequest{}
	mi := &file_brij_storage_v1_wallet_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserDataRequest) ProtoMessage() {}

func (x *GetUserDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_brij_storage_v1_wallet_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserDataRequest.ProtoReflect.Descriptor instead.
func (*GetUserDataRequest) Descriptor() ([]byte, []int) {
	return file_brij_storage_v1_wallet_service_proto_rawDescGZIP(), []int{20}
}

func (x *GetUserDataRequest) GetIncludeValues() bool {
	if x != nil {
		return x.IncludeValues
	}
	return false
}

type GetUserDataResponse struct {
	state          protoimpl.MessageState        `protogen:"open.v1"`
	UserData       []*common.UserDataField       `protobuf:"bytes,1,rep,name=user_data,json=userData,proto3" json:"user_data,omitempty"`
	ValidationData []*common.ValidationDataField `protobuf:"bytes,2,rep,name=validation_data,json=validationData,proto3" json:"validation_data,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetUserDataResponse) Reset() {
	*x = GetUserDataResponse{}
	mi := &file_brij_storage_v1_wallet_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserDataResponse) ProtoMessage() {}

func (x *GetUserDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_brij_storage_v1_wallet_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserDataResponse.ProtoReflect.Descriptor instead.
func (*GetUserDataResponse) Descriptor() ([]byte, []int) {
	return file_brij_storage_v1_wallet_service_proto_rawDescGZIP(), []int{21}
}

func (x *GetUserDataResponse) GetUserData() []*common.UserDataField {
	if x != nil {
		return x.UserData
	}
	return nil
}

func (x *GetUserDataResponse) GetValidationData() []*common.ValidationDataField {
	if x != nil {
		return x.ValidationData
	}
	return nil
}

type CheckAccessRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PartnerPublicKey string                 `protobuf:"bytes,1,opt,name=partner_public_key,json=partnerPublicKey,proto3" json:"partner_public_key,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CheckAccessRequest) Reset() {
	*x = CheckAccessRequest{}
	mi := &file_brij_storage_v1_wallet_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAccessRequest) ProtoMessage() {}

func (x *CheckAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_brij_storage_v1_wallet_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAccessRequest.ProtoReflect.Descriptor instead.
func (*CheckAccessRequest) Descriptor() ([]byte, []int) {
	return file_brij_storage_v1_wallet_service_proto_rawDescGZIP(), []int{22}
}

func (x *CheckAccessRequest) GetPartnerPublicKey() string {
	if x != nil {
		return x.PartnerPublicKey
	}
	return ""
}

type CheckAccessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HasAccess     bool                   `protobuf:"varint,1,opt,name=has_access,json=hasAccess,proto3" json:"has_access,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAccessResponse) Reset() {
	*x = CheckAccessResponse{}
	mi := &file_brij_storage_v1_wallet_service_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAccessResponse) ProtoMessage() {}

func (x *CheckAccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_brij_storage_v1_wallet_service_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAccessResponse.ProtoReflect.Descriptor instead.
func (*CheckAccessResponse) Descriptor() ([]byte, []int) {
	return file_brij_storage_v1_wallet_service_proto_rawDescGZIP(), []int{23}
}

func (x *CheckAccessResponse) GetHasAccess() bool {
	if x != nil {
		return x.HasAccess
	}
	return false
}

type GetKycStatusRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Country            string                 `protobuf:"bytes,1,opt,name=country,proto3" json:"country,omitempty"`
	ValidatorPublicKey string                 `protobuf:"bytes,2,opt,name=validator_public_key,json=validatorPublicKey,proto3" json:"validator_public_key,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetKycStatusRequest) Reset() {
	*x = GetKycStatusRequest{}
	mi := &file_brij_storage_v1_wallet_service_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKycStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKycStatusRequest) ProtoMessage() {}

func (x *GetKycStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_brij_storage_v1_wallet_service_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKycStatusRequest.ProtoReflect.Descriptor instead.
func (*GetKycStatusRequest) Descriptor() ([]byte, []int) {
	return file_brij_storage_v1_wallet_service_proto_rawDescGZIP(), []int{24}
}

func (x *GetKycStatusRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *GetKycStatusRequest) GetValidatorPublicKey() string {
	if x != nil {
		return x.ValidatorPublicKey
	}
	return ""
}

type GetKycStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        common.KycStatus       `protobuf:"varint,1,opt,name=status,proto3,enum=brij.storage.v1.common.KycStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKycStatusResponse) Reset() {
	*x = GetKycStatusResponse{}
	mi := &file_brij_storage_v1_wallet_service_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKycStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKycStatusResponse) ProtoMessage() {}

func (x *GetKycStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_brij_storage_v1_wallet_service_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKycStatusResponse.ProtoReflect.Descriptor instead.
func (*GetKycStatusResponse) Descriptor() ([]byte, []int) {
	return file_brij_storage_v1_wallet_service_proto_rawDescGZIP(), []int{25}
}

func (x *GetKycStatusResponse) GetStatus() common.KycStatus {
	if x != nil {
		return x.Status
	}
	return common.KycStatus(0)
}

type GetWalletProofRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletAddress string                 `protobuf:"bytes,1,opt,name=wallet_address,json=walletAddress,proto3" json:"wallet_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWalletProofRequest) Reset() {
	*x = GetWalletProofRequest{}
	mi := &file_brij_storage_v1_wallet_service_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletProofRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletProofRequest) ProtoMessage() {}

func (x *GetWalletProofRequest) ProtoReflect() protoreflect.Message {
	mi := &file_brij_storage_v1_wallet_service_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletProofRequest.ProtoReflect.Descriptor instead.
func (*GetWalletProofRequest) Descriptor() ([]byte, []int) {
	return file_brij_storage_v1_wallet_service_proto_rawDescGZIP(), []int{26}
}

func (x *GetWalletProofRequest) GetWalletAddress() string {
	if x != nil {
		return x.WalletAddress
	}
	return ""
}

type GetWalletProofResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProofMessage  string                 `protobuf:"bytes,1,opt,name=proof_message,json=proofMessage,proto3" json:"proof_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWalletProofResponse) Reset() {
	*x = GetWalletProofResponse{}
	mi := &file_brij_storage_v1_wallet_service_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletProofResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletProofResponse) ProtoMessage() {}

func (x *GetWalletProofResponse) ProtoReflect() protoreflect.Message {
	mi := &file_brij_storage_v1_wallet_service_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletProofResponse.ProtoReflect.Descriptor instead.
func (*GetWalletProofResponse) Descriptor() ([]byte, []int) {
	return file_brij_storage_v1_wallet_service_proto_rawDescGZIP(), []int{27}
}

func (x *GetWalletProofResponse) GetProofMessage() string {
	if x != nil {
		return x.ProofMessage
	}
	return ""
}

var File_brij_storage_v1_wallet_service_proto protoreflect.FileDescriptor

const file_brij_storage_v1_wallet_service_proto_rawDesc = "" +
	"\n" +
	"$brij/storage/v1/wallet/service.proto\x12\x16brij.storage.v1.wallet\x1a!brij/storage/v1/common/data.proto\x1a%brij/storage/v1/common/kyc_item.proto\x1a,brij/storage/v1/common/user_data_field.proto\x1a2brij/storage/v1/common/validation_data_field.proto\x1a\x1cgoogle/api/annotations.proto\"'\n" +
	"\x15GetPartnerInfoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x89\x01\n" +
	"\x16GetPartnerInfoResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\tR\tpublicKey\x12\x1f\n" +
	"\vprivacy_url\x18\x03 \x01(\tR\n" +
	"privacyUrl\x12\x1b\n" +
	"\tterms_url\x18\x04 \x01(\tR\btermsUrl\"\xbd\x01\n" +
	"\x12InitStorageRequest\x12%\n" +
	"\x0ewallet_address\x18\x01 \x01(\tR\rwalletAddress\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x120\n" +
	"\x14encrypted_secret_key\x18\x03 \x01(\tR\x12encryptedSecretKey\x124\n" +
	"\x16wallet_proof_signature\x18\x04 \x01(\tR\x14walletProofSignature\"\x15\n" +
	"\x13InitStorageResponse\"V\n" +
	"\x0eGetInfoRequest\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\tR\tpublicKey\x12%\n" +
	"\x0ewallet_address\x18\x02 \x01(\tR\rwalletAddress\"\xa3\x01\n" +
	"\x0fGetInfoResponse\x120\n" +
	"\x14encrypted_secret_key\x18\x01 \x01(\tR\x12encryptedSecretKey\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"public_key\x18\x03 \x01(\tR\tpublicKey\x12%\n" +
	"\x0ewallet_address\x18\x04 \x01(\tR\rwalletAddress\"t\n" +
	"\x15GetSeedMessageRequest\x12%\n" +
	"\x0ewallet_address\x18\x01 \x01(\tR\rwalletAddress\x124\n" +
	"\x16wallet_proof_signature\x18\x02 \x01(\tR\x14walletProofSignature\"\x83\x01\n" +
	"\x16GetSeedMessageResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x120\n" +
	"\x14encrypted_secret_key\x18\x02 \x01(\tR\x12encryptedSecretKey\x12\x1d\n" +
	"\n" +
	"public_key\x18\x03 \x01(\tR\tpublicKey\"t\n" +
	"\x12GrantAccessRequest\x12,\n" +
	"\x12partner_public_key\x18\x01 \x01(\tR\x10partnerPublicKey\x120\n" +
	"\x14encrypted_secret_key\x18\x02 \x01(\tR\x12encryptedSecretKey\"\x15\n" +
	"\x13GrantAccessResponse\"C\n" +
	"\x13RevokeAccessRequest\x12,\n" +
	"\x12partner_public_key\x18\x01 \x01(\tR\x10partnerPublicKey\"\x16\n" +
	"\x14RevokeAccessResponse\"\x1a\n" +
	"\x18RemoveAllUserDataRequest\"\x1b\n" +
	"\x19RemoveAllUserDataResponse\"!\n" +
	"\x1fGetGrantedAccessPartnersRequest\"n\n" +
	" GetGrantedAccessPartnersResponse\x12J\n" +
	"\bpartners\x18\x01 \x03(\v2..brij.storage.v1.wallet.GetPartnerInfoResponseR\bpartners\"\xa5\x01\n" +
	"\x12SetUserDataRequest\x124\n" +
	"\x04type\x18\x01 \x01(\x0e2 .brij.storage.v1.common.DataTypeR\x04type\x12'\n" +
	"\x0fencrypted_value\x18\x02 \x01(\fR\x0eencryptedValue\x12\x12\n" +
	"\x04hash\x18\x03 \x01(\tR\x04hash\x12\x1c\n" +
	"\tsignature\x18\x04 \x01(\tR\tsignature\"\x15\n" +
	"\x13SetUserDataResponse\"'\n" +
	"\x15RemoveUserDataRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x18\n" +
	"\x16RemoveUserDataResponse\";\n" +
	"\x12GetUserDataRequest\x12%\n" +
	"\x0einclude_values\x18\x01 \x01(\bR\rincludeValues\"\xaf\x01\n" +
	"\x13GetUserDataResponse\x12B\n" +
	"\tuser_data\x18\x01 \x03(\v2%.brij.storage.v1.common.UserDataFieldR\buserData\x12T\n" +
	"\x0fvalidation_data\x18\x02 \x03(\v2+.brij.storage.v1.common.ValidationDataFieldR\x0evalidationData\"B\n" +
	"\x12CheckAccessRequest\x12,\n" +
	"\x12partner_public_key\x18\x01 \x01(\tR\x10partnerPublicKey\"4\n" +
	"\x13CheckAccessResponse\x12\x1d\n" +
	"\n" +
	"has_access\x18\x01 \x01(\bR\thasAccess\"a\n" +
	"\x13GetKycStatusRequest\x12\x18\n" +
	"\acountry\x18\x01 \x01(\tR\acountry\x120\n" +
	"\x14validator_public_key\x18\x02 \x01(\tR\x12validatorPublicKey\"Q\n" +
	"\x14GetKycStatusResponse\x129\n" +
	"\x06status\x18\x01 \x01(\x0e2!.brij.storage.v1.common.KycStatusR\x06status\">\n" +
	"\x15GetWalletProofRequest\x12%\n" +
	"\x0ewallet_address\x18\x01 \x01(\tR\rwalletAddress\"=\n" +
	"\x16GetWalletProofResponse\x12#\n" +
	"\rproof_message\x18\x01 \x01(\tR\fproofMessage2\x80\x10\n" +
	"\rWalletService\x12\x92\x01\n" +
	"\x0eGetPartnerInfo\x12-.brij.storage.v1.wallet.GetPartnerInfoRequest\x1a..brij.storage.v1.wallet.GetPartnerInfoResponse\"!\x82\xd3\xe4\x93\x02\x1b\"\x19/v1/wallet/getPartnerInfo\x12\x86\x01\n" +
	"\vInitStorage\x12*.brij.storage.v1.wallet.InitStorageRequest\x1a+.brij.storage.v1.wallet.InitStorageResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\"\x16/v1/wallet/initStorage\x12v\n" +
	"\aGetInfo\x12&.brij.storage.v1.wallet.GetInfoRequest\x1a'.brij.storage.v1.wallet.GetInfoResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\"\x12/v1/wallet/getInfo\x12\xba\x01\n" +
	"\x18GetGrantedAccessPartners\x127.brij.storage.v1.wallet.GetGrantedAccessPartnersRequest\x1a8.brij.storage.v1.wallet.GetGrantedAccessPartnersResponse\"+\x82\xd3\xe4\x93\x02%\"#/v1/wallet/getGrantedAccessPartners\x12\x86\x01\n" +
	"\vGrantAccess\x12*.brij.storage.v1.wallet.GrantAccessRequest\x1a+.brij.storage.v1.wallet.GrantAccessResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\"\x16/v1/wallet/grantAccess\x12\x86\x01\n" +
	"\vSetUserData\x12*.brij.storage.v1.wallet.SetUserDataRequest\x1a+.brij.storage.v1.wallet.SetUserDataResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\"\x16/v1/wallet/setUserData\x12\x92\x01\n" +
	"\x0eRemoveUserData\x12-.brij.storage.v1.wallet.RemoveUserDataRequest\x1a..brij.storage.v1.wallet.RemoveUserDataResponse\"!\x82\xd3\xe4\x93\x02\x1b\"\x19/v1/wallet/removeUserData\x12\x8a\x01\n" +
	"\fRevokeAccess\x12+.brij.storage.v1.wallet.RevokeAccessRequest\x1a,.brij.storage.v1.wallet.RevokeAccessResponse\"\x1f\x82\xd3\xe4\x93\x02\x19\"\x17/v1/wallet/revokeAccess\x12\x9e\x01\n" +
	"\x11RemoveAllUserData\x120.brij.storage.v1.wallet.RemoveAllUserDataRequest\x1a1.brij.storage.v1.wallet.RemoveAllUserDataResponse\"$\x82\xd3\xe4\x93\x02\x1e\"\x1c/v1/wallet/removeAllUserData\x12\x86\x01\n" +
	"\vGetUserData\x12*.brij.storage.v1.wallet.GetUserDataRequest\x1a+.brij.storage.v1.wallet.GetUserDataResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\"\x16/v1/wallet/getUserData\x12\x86\x01\n" +
	"\vCheckAccess\x12*.brij.storage.v1.wallet.CheckAccessRequest\x1a+.brij.storage.v1.wallet.CheckAccessResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\"\x16/v1/wallet/checkAccess\x12\x8a\x01\n" +
	"\fGetKycStatus\x12+.brij.storage.v1.wallet.GetKycStatusRequest\x1a,.brij.storage.v1.wallet.GetKycStatusResponse\"\x1f\x82\xd3\xe4\x93\x02\x19\"\x17/v1/wallet/getKycStatus\x12\x92\x01\n" +
	"\x0eGetWalletProof\x12-.brij.storage.v1.wallet.GetWalletProofRequest\x1a..brij.storage.v1.wallet.GetWalletProofResponse\"!\x82\xd3\xe4\x93\x02\x1b\"\x19/v1/wallet/getWalletProof\x12\x92\x01\n" +
	"\x0eGetSeedMessage\x12-.brij.storage.v1.wallet.GetSeedMessageRequest\x1a..brij.storage.v1.wallet.GetSeedMessageResponse\"!\x82\xd3\xe4\x93\x02\x1b\"\x19/v1/wallet/getSeedMessageB*Z(go.brij.fi/protos/brij/storage/v1/walletb\x06proto3"

var (
	file_brij_storage_v1_wallet_service_proto_rawDescOnce sync.Once
	file_brij_storage_v1_wallet_service_proto_rawDescData []byte
)

func file_brij_storage_v1_wallet_service_proto_rawDescGZIP() []byte {
	file_brij_storage_v1_wallet_service_proto_rawDescOnce.Do(func() {
		file_brij_storage_v1_wallet_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_brij_storage_v1_wallet_service_proto_rawDesc), len(file_brij_storage_v1_wallet_service_proto_rawDesc)))
	})
	return file_brij_storage_v1_wallet_service_proto_rawDescData
}

var file_brij_storage_v1_wallet_service_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_brij_storage_v1_wallet_service_proto_goTypes = []any{
	(*GetPartnerInfoRequest)(nil),            // 0: brij.storage.v1.wallet.GetPartnerInfoRequest
	(*GetPartnerInfoResponse)(nil),           // 1: brij.storage.v1.wallet.GetPartnerInfoResponse
	(*InitStorageRequest)(nil),               // 2: brij.storage.v1.wallet.InitStorageRequest
	(*InitStorageResponse)(nil),              // 3: brij.storage.v1.wallet.InitStorageResponse
	(*GetInfoRequest)(nil),                   // 4: brij.storage.v1.wallet.GetInfoRequest
	(*GetInfoResponse)(nil),                  // 5: brij.storage.v1.wallet.GetInfoResponse
	(*GetSeedMessageRequest)(nil),            // 6: brij.storage.v1.wallet.GetSeedMessageRequest
	(*GetSeedMessageResponse)(nil),           // 7: brij.storage.v1.wallet.GetSeedMessageResponse
	(*GrantAccessRequest)(nil),               // 8: brij.storage.v1.wallet.GrantAccessRequest
	(*GrantAccessResponse)(nil),              // 9: brij.storage.v1.wallet.GrantAccessResponse
	(*RevokeAccessRequest)(nil),              // 10: brij.storage.v1.wallet.RevokeAccessRequest
	(*RevokeAccessResponse)(nil),             // 11: brij.storage.v1.wallet.RevokeAccessResponse
	(*RemoveAllUserDataRequest)(nil),         // 12: brij.storage.v1.wallet.RemoveAllUserDataRequest
	(*RemoveAllUserDataResponse)(nil),        // 13: brij.storage.v1.wallet.RemoveAllUserDataResponse
	(*GetGrantedAccessPartnersRequest)(nil),  // 14: brij.storage.v1.wallet.GetGrantedAccessPartnersRequest
	(*GetGrantedAccessPartnersResponse)(nil), // 15: brij.storage.v1.wallet.GetGrantedAccessPartnersResponse
	(*SetUserDataRequest)(nil),               // 16: brij.storage.v1.wallet.SetUserDataRequest
	(*SetUserDataResponse)(nil),              // 17: brij.storage.v1.wallet.SetUserDataResponse
	(*RemoveUserDataRequest)(nil),            // 18: brij.storage.v1.wallet.RemoveUserDataRequest
	(*RemoveUserDataResponse)(nil),           // 19: brij.storage.v1.wallet.RemoveUserDataResponse
	(*GetUserDataRequest)(nil),               // 20: brij.storage.v1.wallet.GetUserDataRequest
	(*GetUserDataResponse)(nil),              // 21: brij.storage.v1.wallet.GetUserDataResponse
	(*CheckAccessRequest)(nil),               // 22: brij.storage.v1.wallet.CheckAccessRequest
	(*CheckAccessResponse)(nil),              // 23: brij.storage.v1.wallet.CheckAccessResponse
	(*GetKycStatusRequest)(nil),              // 24: brij.storage.v1.wallet.GetKycStatusRequest
	(*GetKycStatusResponse)(nil),             // 25: brij.storage.v1.wallet.GetKycStatusResponse
	(*GetWalletProofRequest)(nil),            // 26: brij.storage.v1.wallet.GetWalletProofRequest
	(*GetWalletProofResponse)(nil),           // 27: brij.storage.v1.wallet.GetWalletProofResponse
	(common.DataType)(0),                     // 28: brij.storage.v1.common.DataType
	(*common.UserDataField)(nil),             // 29: brij.storage.v1.common.UserDataField
	(*common.ValidationDataField)(nil),       // 30: brij.storage.v1.common.ValidationDataField
	(common.KycStatus)(0),                    // 31: brij.storage.v1.common.KycStatus
}
var file_brij_storage_v1_wallet_service_proto_depIdxs = []int32{
	1,  // 0: brij.storage.v1.wallet.GetGrantedAccessPartnersResponse.partners:type_name -> brij.storage.v1.wallet.GetPartnerInfoResponse
	28, // 1: brij.storage.v1.wallet.SetUserDataRequest.type:type_name -> brij.storage.v1.common.DataType
	29, // 2: brij.storage.v1.wallet.GetUserDataResponse.user_data:type_name -> brij.storage.v1.common.UserDataField
	30, // 3: brij.storage.v1.wallet.GetUserDataResponse.validation_data:type_name -> brij.storage.v1.common.ValidationDataField
	31, // 4: brij.storage.v1.wallet.GetKycStatusResponse.status:type_name -> brij.storage.v1.common.KycStatus
	0,  // 5: brij.storage.v1.wallet.WalletService.GetPartnerInfo:input_type -> brij.storage.v1.wallet.GetPartnerInfoRequest
	2,  // 6: brij.storage.v1.wallet.WalletService.InitStorage:input_type -> brij.storage.v1.wallet.InitStorageRequest
	4,  // 7: brij.storage.v1.wallet.WalletService.GetInfo:input_type -> brij.storage.v1.wallet.GetInfoRequest
	14, // 8: brij.storage.v1.wallet.WalletService.GetGrantedAccessPartners:input_type -> brij.storage.v1.wallet.GetGrantedAccessPartnersRequest
	8,  // 9: brij.storage.v1.wallet.WalletService.GrantAccess:input_type -> brij.storage.v1.wallet.GrantAccessRequest
	16, // 10: brij.storage.v1.wallet.WalletService.SetUserData:input_type -> brij.storage.v1.wallet.SetUserDataRequest
	18, // 11: brij.storage.v1.wallet.WalletService.RemoveUserData:input_type -> brij.storage.v1.wallet.RemoveUserDataRequest
	10, // 12: brij.storage.v1.wallet.WalletService.RevokeAccess:input_type -> brij.storage.v1.wallet.RevokeAccessRequest
	12, // 13: brij.storage.v1.wallet.WalletService.RemoveAllUserData:input_type -> brij.storage.v1.wallet.RemoveAllUserDataRequest
	20, // 14: brij.storage.v1.wallet.WalletService.GetUserData:input_type -> brij.storage.v1.wallet.GetUserDataRequest
	22, // 15: brij.storage.v1.wallet.WalletService.CheckAccess:input_type -> brij.storage.v1.wallet.CheckAccessRequest
	24, // 16: brij.storage.v1.wallet.WalletService.GetKycStatus:input_type -> brij.storage.v1.wallet.GetKycStatusRequest
	26, // 17: brij.storage.v1.wallet.WalletService.GetWalletProof:input_type -> brij.storage.v1.wallet.GetWalletProofRequest
	6,  // 18: brij.storage.v1.wallet.WalletService.GetSeedMessage:input_type -> brij.storage.v1.wallet.GetSeedMessageRequest
	1,  // 19: brij.storage.v1.wallet.WalletService.GetPartnerInfo:output_type -> brij.storage.v1.wallet.GetPartnerInfoResponse
	3,  // 20: brij.storage.v1.wallet.WalletService.InitStorage:output_type -> brij.storage.v1.wallet.InitStorageResponse
	5,  // 21: brij.storage.v1.wallet.WalletService.GetInfo:output_type -> brij.storage.v1.wallet.GetInfoResponse
	15, // 22: brij.storage.v1.wallet.WalletService.GetGrantedAccessPartners:output_type -> brij.storage.v1.wallet.GetGrantedAccessPartnersResponse
	9,  // 23: brij.storage.v1.wallet.WalletService.GrantAccess:output_type -> brij.storage.v1.wallet.GrantAccessResponse
	17, // 24: brij.storage.v1.wallet.WalletService.SetUserData:output_type -> brij.storage.v1.wallet.SetUserDataResponse
	19, // 25: brij.storage.v1.wallet.WalletService.RemoveUserData:output_type -> brij.storage.v1.wallet.RemoveUserDataResponse
	11, // 26: brij.storage.v1.wallet.WalletService.RevokeAccess:output_type -> brij.storage.v1.wallet.RevokeAccessResponse
	13, // 27: brij.storage.v1.wallet.WalletService.RemoveAllUserData:output_type -> brij.storage.v1.wallet.RemoveAllUserDataResponse
	21, // 28: brij.storage.v1.wallet.WalletService.GetUserData:output_type -> brij.storage.v1.wallet.GetUserDataResponse
	23, // 29: brij.storage.v1.wallet.WalletService.CheckAccess:output_type -> brij.storage.v1.wallet.CheckAccessResponse
	25, // 30: brij.storage.v1.wallet.WalletService.GetKycStatus:output_type -> brij.storage.v1.wallet.GetKycStatusResponse
	27, // 31: brij.storage.v1.wallet.WalletService.GetWalletProof:output_type -> brij.storage.v1.wallet.GetWalletProofResponse
	7,  // 32: brij.storage.v1.wallet.WalletService.GetSeedMessage:output_type -> brij.storage.v1.wallet.GetSeedMessageResponse
	19, // [19:33] is the sub-list for method output_type
	5,  // [5:19] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_brij_storage_v1_wallet_service_proto_init() }
func file_brij_storage_v1_wallet_service_proto_init() {
	if File_brij_storage_v1_wallet_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_brij_storage_v1_wallet_service_proto_rawDesc), len(file_brij_storage_v1_wallet_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_brij_storage_v1_wallet_service_proto_goTypes,
		DependencyIndexes: file_brij_storage_v1_wallet_service_proto_depIdxs,
		MessageInfos:      file_brij_storage_v1_wallet_service_proto_msgTypes,
	}.Build()
	File_brij_storage_v1_wallet_service_proto = out.File
	file_brij_storage_v1_wallet_service_proto_goTypes = nil
	file_brij_storage_v1_wallet_service_proto_depIdxs = nil
}
