// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: brij/orders/v1/common/ramp_type.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RampType int32

const (
	RampType_RAMP_TYPE_UNSPECIFIED RampType = 0
	RampType_RAMP_TYPE_ON_RAMP     RampType = 1
	RampType_RAMP_TYPE_OFF_RAMP    RampType = 2
)

// Enum value maps for RampType.
var (
	RampType_name = map[int32]string{
		0: "RAMP_TYPE_UNSPECIFIED",
		1: "RAMP_TYPE_ON_RAMP",
		2: "RAMP_TYPE_OFF_RAMP",
	}
	RampType_value = map[string]int32{
		"RAMP_TYPE_UNSPECIFIED": 0,
		"RAMP_TYPE_ON_RAMP":     1,
		"RAMP_TYPE_OFF_RAMP":    2,
	}
)

func (x RampType) Enum() *RampType {
	p := new(RampType)
	*p = x
	return p
}

func (x RampType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RampType) Descriptor() protoreflect.EnumDescriptor {
	return file_brij_orders_v1_common_ramp_type_proto_enumTypes[0].Descriptor()
}

func (RampType) Type() protoreflect.EnumType {
	return &file_brij_orders_v1_common_ramp_type_proto_enumTypes[0]
}

func (x RampType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RampType.Descriptor instead.
func (RampType) EnumDescriptor() ([]byte, []int) {
	return file_brij_orders_v1_common_ramp_type_proto_rawDescGZIP(), []int{0}
}

var File_brij_orders_v1_common_ramp_type_proto protoreflect.FileDescriptor

const file_brij_orders_v1_common_ramp_type_proto_rawDesc = "" +
	"\n" +
	"%brij/orders/v1/common/ramp_type.proto\x12\x15brij.orders.v1.common*T\n" +
	"\bRampType\x12\x19\n" +
	"\x15RAMP_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11RAMP_TYPE_ON_RAMP\x10\x01\x12\x16\n" +
	"\x12RAMP_TYPE_OFF_RAMP\x10\x02B)Z'go.brij.fi/protos/brij/orders/v1/commonb\x06proto3"

var (
	file_brij_orders_v1_common_ramp_type_proto_rawDescOnce sync.Once
	file_brij_orders_v1_common_ramp_type_proto_rawDescData []byte
)

func file_brij_orders_v1_common_ramp_type_proto_rawDescGZIP() []byte {
	file_brij_orders_v1_common_ramp_type_proto_rawDescOnce.Do(func() {
		file_brij_orders_v1_common_ramp_type_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_brij_orders_v1_common_ramp_type_proto_rawDesc), len(file_brij_orders_v1_common_ramp_type_proto_rawDesc)))
	})
	return file_brij_orders_v1_common_ramp_type_proto_rawDescData
}

var file_brij_orders_v1_common_ramp_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_brij_orders_v1_common_ramp_type_proto_goTypes = []any{
	(RampType)(0), // 0: brij.orders.v1.common.RampType
}
var file_brij_orders_v1_common_ramp_type_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_brij_orders_v1_common_ramp_type_proto_init() }
func file_brij_orders_v1_common_ramp_type_proto_init() {
	if File_brij_orders_v1_common_ramp_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_brij_orders_v1_common_ramp_type_proto_rawDesc), len(file_brij_orders_v1_common_ramp_type_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_brij_orders_v1_common_ramp_type_proto_goTypes,
		DependencyIndexes: file_brij_orders_v1_common_ramp_type_proto_depIdxs,
		EnumInfos:         file_brij_orders_v1_common_ramp_type_proto_enumTypes,
	}.Build()
	File_brij_orders_v1_common_ramp_type_proto = out.File
	file_brij_orders_v1_common_ramp_type_proto_goTypes = nil
	file_brij_orders_v1_common_ramp_type_proto_depIdxs = nil
}
