// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: brij/orders/v1/common/ramp_type.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RampType int32

const (
	RampType_RAMP_TYPE_UNSPECIFIED RampType = 0
	RampType_RAMP_TYPE_ON_RAMP     RampType = 1
	RampType_RAMP_TYPE_OFF_RAMP    RampType = 2
)

// Enum value maps for RampType.
var (
	RampType_name = map[int32]string{
		0: "RAMP_TYPE_UNSPECIFIED",
		1: "RAMP_TYPE_ON_RAMP",
		2: "RAMP_TYPE_OFF_RAMP",
	}
	RampType_value = map[string]int32{
		"RAMP_TYPE_UNSPECIFIED": 0,
		"RAMP_TYPE_ON_RAMP":     1,
		"RAMP_TYPE_OFF_RAMP":    2,
	}
)

func (x RampType) Enum() *RampType {
	p := new(RampType)
	*p = x
	return p
}

func (x RampType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RampType) Descriptor() protoreflect.EnumDescriptor {
	return file_brij_orders_v1_common_ramp_type_proto_enumTypes[0].Descriptor()
}

func (RampType) Type() protoreflect.EnumType {
	return &file_brij_orders_v1_common_ramp_type_proto_enumTypes[0]
}

func (x RampType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RampType.Descriptor instead.
func (RampType) EnumDescriptor() ([]byte, []int) {
	return file_brij_orders_v1_common_ramp_type_proto_rawDescGZIP(), []int{0}
}

var File_brij_orders_v1_common_ramp_type_proto protoreflect.FileDescriptor

var file_brij_orders_v1_common_ramp_type_proto_rawDesc = []byte{
	0x0a, 0x25, 0x62, 0x72, 0x69, 0x6a, 0x2f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x2f, 0x76, 0x31,
	0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x72, 0x61, 0x6d, 0x70, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x15, 0x62, 0x72, 0x69, 0x6a, 0x2e, 0x6f, 0x72,
	0x64, 0x65, 0x72, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2a, 0x54,
	0x0a, 0x08, 0x52, 0x61, 0x6d, 0x70, 0x54, 0x79, 0x70, 0x65, 0x12, 0x19, 0x0a, 0x15, 0x52, 0x41,
	0x4d, 0x50, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46,
	0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x15, 0x0a, 0x11, 0x52, 0x41, 0x4d, 0x50, 0x5f, 0x54, 0x59,
	0x50, 0x45, 0x5f, 0x4f, 0x4e, 0x5f, 0x52, 0x41, 0x4d, 0x50, 0x10, 0x01, 0x12, 0x16, 0x0a, 0x12,
	0x52, 0x41, 0x4d, 0x50, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x4f, 0x46, 0x46, 0x5f, 0x52, 0x41,
	0x4d, 0x50, 0x10, 0x02, 0x42, 0x29, 0x5a, 0x27, 0x67, 0x6f, 0x2e, 0x62, 0x72, 0x69, 0x6a, 0x2e,
	0x66, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x62, 0x72, 0x69, 0x6a, 0x2f, 0x6f,
	0x72, 0x64, 0x65, 0x72, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_brij_orders_v1_common_ramp_type_proto_rawDescOnce sync.Once
	file_brij_orders_v1_common_ramp_type_proto_rawDescData = file_brij_orders_v1_common_ramp_type_proto_rawDesc
)

func file_brij_orders_v1_common_ramp_type_proto_rawDescGZIP() []byte {
	file_brij_orders_v1_common_ramp_type_proto_rawDescOnce.Do(func() {
		file_brij_orders_v1_common_ramp_type_proto_rawDescData = protoimpl.X.CompressGZIP(file_brij_orders_v1_common_ramp_type_proto_rawDescData)
	})
	return file_brij_orders_v1_common_ramp_type_proto_rawDescData
}

var file_brij_orders_v1_common_ramp_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_brij_orders_v1_common_ramp_type_proto_goTypes = []any{
	(RampType)(0), // 0: brij.orders.v1.common.RampType
}
var file_brij_orders_v1_common_ramp_type_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_brij_orders_v1_common_ramp_type_proto_init() }
func file_brij_orders_v1_common_ramp_type_proto_init() {
	if File_brij_orders_v1_common_ramp_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_brij_orders_v1_common_ramp_type_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_brij_orders_v1_common_ramp_type_proto_goTypes,
		DependencyIndexes: file_brij_orders_v1_common_ramp_type_proto_depIdxs,
		EnumInfos:         file_brij_orders_v1_common_ramp_type_proto_enumTypes,
	}.Build()
	File_brij_orders_v1_common_ramp_type_proto = out.File
	file_brij_orders_v1_common_ramp_type_proto_rawDesc = nil
	file_brij_orders_v1_common_ramp_type_proto_goTypes = nil
	file_brij_orders_v1_common_ramp_type_proto_depIdxs = nil
}
