// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: brij/verifier/v1/get_kyc_requirements.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetKycRequirementsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Country string `protobuf:"bytes,1,opt,name=country,proto3" json:"country,omitempty"`
}

func (x *GetKycRequirementsRequest) Reset() {
	*x = GetKycRequirementsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_brij_verifier_v1_get_kyc_requirements_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetKycRequirementsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKycRequirementsRequest) ProtoMessage() {}

func (x *GetKycRequirementsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_brij_verifier_v1_get_kyc_requirements_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKycRequirementsRequest.ProtoReflect.Descriptor instead.
func (*GetKycRequirementsRequest) Descriptor() ([]byte, []int) {
	return file_brij_verifier_v1_get_kyc_requirements_proto_rawDescGZIP(), []int{0}
}

func (x *GetKycRequirementsRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

type GetKycRequirementsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Country      string         `protobuf:"bytes,1,opt,name=country,proto3" json:"country,omitempty"`
	Requirements []*Requirement `protobuf:"bytes,2,rep,name=requirements,proto3" json:"requirements,omitempty"`
}

func (x *GetKycRequirementsResponse) Reset() {
	*x = GetKycRequirementsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_brij_verifier_v1_get_kyc_requirements_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetKycRequirementsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKycRequirementsResponse) ProtoMessage() {}

func (x *GetKycRequirementsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_brij_verifier_v1_get_kyc_requirements_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKycRequirementsResponse.ProtoReflect.Descriptor instead.
func (*GetKycRequirementsResponse) Descriptor() ([]byte, []int) {
	return file_brij_verifier_v1_get_kyc_requirements_proto_rawDescGZIP(), []int{1}
}

func (x *GetKycRequirementsResponse) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *GetKycRequirementsResponse) GetRequirements() []*Requirement {
	if x != nil {
		return x.Requirements
	}
	return nil
}

type Requirement struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type    DataType `protobuf:"varint,1,opt,name=type,proto3,enum=brij.verifier.v1.DataType" json:"type,omitempty"`
	Formula *Formula `protobuf:"bytes,2,opt,name=formula,proto3" json:"formula,omitempty"`
}

func (x *Requirement) Reset() {
	*x = Requirement{}
	if protoimpl.UnsafeEnabled {
		mi := &file_brij_verifier_v1_get_kyc_requirements_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Requirement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Requirement) ProtoMessage() {}

func (x *Requirement) ProtoReflect() protoreflect.Message {
	mi := &file_brij_verifier_v1_get_kyc_requirements_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Requirement.ProtoReflect.Descriptor instead.
func (*Requirement) Descriptor() ([]byte, []int) {
	return file_brij_verifier_v1_get_kyc_requirements_proto_rawDescGZIP(), []int{2}
}

func (x *Requirement) GetType() DataType {
	if x != nil {
		return x.Type
	}
	return DataType_DATA_TYPE_UNSPECIFIED
}

func (x *Requirement) GetFormula() *Formula {
	if x != nil {
		return x.Formula
	}
	return nil
}

type Formula struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Value:
	//
	//	*Formula_And
	//	*Formula_Or
	//	*Formula_Not
	//	*Formula_Constant
	//	*Formula_Condition_
	Value isFormula_Value `protobuf_oneof:"value"`
}

func (x *Formula) Reset() {
	*x = Formula{}
	if protoimpl.UnsafeEnabled {
		mi := &file_brij_verifier_v1_get_kyc_requirements_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Formula) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Formula) ProtoMessage() {}

func (x *Formula) ProtoReflect() protoreflect.Message {
	mi := &file_brij_verifier_v1_get_kyc_requirements_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Formula.ProtoReflect.Descriptor instead.
func (*Formula) Descriptor() ([]byte, []int) {
	return file_brij_verifier_v1_get_kyc_requirements_proto_rawDescGZIP(), []int{3}
}

func (m *Formula) GetValue() isFormula_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (x *Formula) GetAnd() *Formula_Nested {
	if x, ok := x.GetValue().(*Formula_And); ok {
		return x.And
	}
	return nil
}

func (x *Formula) GetOr() *Formula_Nested {
	if x, ok := x.GetValue().(*Formula_Or); ok {
		return x.Or
	}
	return nil
}

func (x *Formula) GetNot() *Formula {
	if x, ok := x.GetValue().(*Formula_Not); ok {
		return x.Not
	}
	return nil
}

func (x *Formula) GetConstant() bool {
	if x, ok := x.GetValue().(*Formula_Constant); ok {
		return x.Constant
	}
	return false
}

func (x *Formula) GetCondition() *Formula_Condition {
	if x, ok := x.GetValue().(*Formula_Condition_); ok {
		return x.Condition
	}
	return nil
}

type isFormula_Value interface {
	isFormula_Value()
}

type Formula_And struct {
	And *Formula_Nested `protobuf:"bytes,1,opt,name=and,proto3,oneof"`
}

type Formula_Or struct {
	Or *Formula_Nested `protobuf:"bytes,2,opt,name=or,proto3,oneof"`
}

type Formula_Not struct {
	Not *Formula `protobuf:"bytes,3,opt,name=not,proto3,oneof"`
}

type Formula_Constant struct {
	Constant bool `protobuf:"varint,4,opt,name=constant,proto3,oneof"`
}

type Formula_Condition_ struct {
	Condition *Formula_Condition `protobuf:"bytes,5,opt,name=condition,proto3,oneof"`
}

func (*Formula_And) isFormula_Value() {}

func (*Formula_Or) isFormula_Value() {}

func (*Formula_Not) isFormula_Value() {}

func (*Formula_Constant) isFormula_Value() {}

func (*Formula_Condition_) isFormula_Value() {}

type Formula_Nested struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Formulas []*Formula `protobuf:"bytes,1,rep,name=formulas,proto3" json:"formulas,omitempty"`
}

func (x *Formula_Nested) Reset() {
	*x = Formula_Nested{}
	if protoimpl.UnsafeEnabled {
		mi := &file_brij_verifier_v1_get_kyc_requirements_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Formula_Nested) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Formula_Nested) ProtoMessage() {}

func (x *Formula_Nested) ProtoReflect() protoreflect.Message {
	mi := &file_brij_verifier_v1_get_kyc_requirements_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Formula_Nested.ProtoReflect.Descriptor instead.
func (*Formula_Nested) Descriptor() ([]byte, []int) {
	return file_brij_verifier_v1_get_kyc_requirements_proto_rawDescGZIP(), []int{3, 0}
}

func (x *Formula_Nested) GetFormulas() []*Formula {
	if x != nil {
		return x.Formulas
	}
	return nil
}

type Formula_Condition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Value:
	//
	//	*Formula_Condition_CountryCode
	//	*Formula_Condition_DocumentType
	//	*Formula_Condition_DocumentField
	Value isFormula_Condition_Value `protobuf_oneof:"value"`
}

func (x *Formula_Condition) Reset() {
	*x = Formula_Condition{}
	if protoimpl.UnsafeEnabled {
		mi := &file_brij_verifier_v1_get_kyc_requirements_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Formula_Condition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Formula_Condition) ProtoMessage() {}

func (x *Formula_Condition) ProtoReflect() protoreflect.Message {
	mi := &file_brij_verifier_v1_get_kyc_requirements_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Formula_Condition.ProtoReflect.Descriptor instead.
func (*Formula_Condition) Descriptor() ([]byte, []int) {
	return file_brij_verifier_v1_get_kyc_requirements_proto_rawDescGZIP(), []int{3, 1}
}

func (m *Formula_Condition) GetValue() isFormula_Condition_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (x *Formula_Condition) GetCountryCode() string {
	if x, ok := x.GetValue().(*Formula_Condition_CountryCode); ok {
		return x.CountryCode
	}
	return ""
}

func (x *Formula_Condition) GetDocumentType() DocumentType {
	if x, ok := x.GetValue().(*Formula_Condition_DocumentType); ok {
		return x.DocumentType
	}
	return DocumentType_DOCUMENT_TYPE_UNSPECIFIED
}

func (x *Formula_Condition) GetDocumentField() DocumentFieldType {
	if x, ok := x.GetValue().(*Formula_Condition_DocumentField); ok {
		return x.DocumentField
	}
	return DocumentFieldType_DOCUMENT_FIELD_TYPE_UNSPECIFIED
}

type isFormula_Condition_Value interface {
	isFormula_Condition_Value()
}

type Formula_Condition_CountryCode struct {
	CountryCode string `protobuf:"bytes,1,opt,name=country_code,json=countryCode,proto3,oneof"`
}

type Formula_Condition_DocumentType struct {
	DocumentType DocumentType `protobuf:"varint,2,opt,name=document_type,json=documentType,proto3,enum=brij.verifier.v1.DocumentType,oneof"`
}

type Formula_Condition_DocumentField struct {
	DocumentField DocumentFieldType `protobuf:"varint,3,opt,name=document_field,json=documentField,proto3,enum=brij.verifier.v1.DocumentFieldType,oneof"`
}

func (*Formula_Condition_CountryCode) isFormula_Condition_Value() {}

func (*Formula_Condition_DocumentType) isFormula_Condition_Value() {}

func (*Formula_Condition_DocumentField) isFormula_Condition_Value() {}

var File_brij_verifier_v1_get_kyc_requirements_proto protoreflect.FileDescriptor

var file_brij_verifier_v1_get_kyc_requirements_proto_rawDesc = []byte{
	0x0a, 0x2b, 0x62, 0x72, 0x69, 0x6a, 0x2f, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x72, 0x2f,
	0x76, 0x31, 0x2f, 0x67, 0x65, 0x74, 0x5f, 0x6b, 0x79, 0x63, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x69,
	0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x62,
	0x72, 0x69, 0x6a, 0x2e, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x1a,
	0x1b, 0x62, 0x72, 0x69, 0x6a, 0x2f, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x72, 0x2f, 0x76,
	0x31, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x35, 0x0a, 0x19,
	0x47, 0x65, 0x74, 0x4b, 0x79, 0x63, 0x52, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x72, 0x79, 0x22, 0x79, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x4b, 0x79, 0x63, 0x52, 0x65, 0x71,
	0x75, 0x69, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x41, 0x0a, 0x0c, 0x72,
	0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x1d, 0x2e, 0x62, 0x72, 0x69, 0x6a, 0x2e, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65,
	0x72, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74,
	0x52, 0x0c, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x72,
	0x0a, 0x0b, 0x52, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x2e, 0x0a,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1a, 0x2e, 0x62, 0x72,
	0x69, 0x6a, 0x2e, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x44,
	0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x33, 0x0a,
	0x07, 0x66, 0x6f, 0x72, 0x6d, 0x75, 0x6c, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19,
	0x2e, 0x62, 0x72, 0x69, 0x6a, 0x2e, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x72, 0x2e, 0x76,
	0x31, 0x2e, 0x46, 0x6f, 0x72, 0x6d, 0x75, 0x6c, 0x61, 0x52, 0x07, 0x66, 0x6f, 0x72, 0x6d, 0x75,
	0x6c, 0x61, 0x22, 0xa0, 0x04, 0x0a, 0x07, 0x46, 0x6f, 0x72, 0x6d, 0x75, 0x6c, 0x61, 0x12, 0x34,
	0x0a, 0x03, 0x61, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x62, 0x72,
	0x69, 0x6a, 0x2e, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x46,
	0x6f, 0x72, 0x6d, 0x75, 0x6c, 0x61, 0x2e, 0x4e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x48, 0x00, 0x52,
	0x03, 0x61, 0x6e, 0x64, 0x12, 0x32, 0x0a, 0x02, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x20, 0x2e, 0x62, 0x72, 0x69, 0x6a, 0x2e, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x72,
	0x2e, 0x76, 0x31, 0x2e, 0x46, 0x6f, 0x72, 0x6d, 0x75, 0x6c, 0x61, 0x2e, 0x4e, 0x65, 0x73, 0x74,
	0x65, 0x64, 0x48, 0x00, 0x52, 0x02, 0x6f, 0x72, 0x12, 0x2d, 0x0a, 0x03, 0x6e, 0x6f, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x62, 0x72, 0x69, 0x6a, 0x2e, 0x76, 0x65, 0x72,
	0x69, 0x66, 0x69, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x6f, 0x72, 0x6d, 0x75, 0x6c, 0x61,
	0x48, 0x00, 0x52, 0x03, 0x6e, 0x6f, 0x74, 0x12, 0x1c, 0x0a, 0x08, 0x63, 0x6f, 0x6e, 0x73, 0x74,
	0x61, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x08, 0x63, 0x6f, 0x6e,
	0x73, 0x74, 0x61, 0x6e, 0x74, 0x12, 0x43, 0x0a, 0x09, 0x63, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x62, 0x72, 0x69, 0x6a, 0x2e,
	0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x6f, 0x72, 0x6d,
	0x75, 0x6c, 0x61, 0x2e, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52,
	0x09, 0x63, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x3f, 0x0a, 0x06, 0x4e, 0x65,
	0x73, 0x74, 0x65, 0x64, 0x12, 0x35, 0x0a, 0x08, 0x66, 0x6f, 0x72, 0x6d, 0x75, 0x6c, 0x61, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x62, 0x72, 0x69, 0x6a, 0x2e, 0x76, 0x65,
	0x72, 0x69, 0x66, 0x69, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x6f, 0x72, 0x6d, 0x75, 0x6c,
	0x61, 0x52, 0x08, 0x66, 0x6f, 0x72, 0x6d, 0x75, 0x6c, 0x61, 0x73, 0x1a, 0xce, 0x01, 0x0a, 0x09,
	0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x23, 0x0a, 0x0c, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x72, 0x79, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x00, 0x52, 0x0b, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x45,
	0x0a, 0x0d, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1e, 0x2e, 0x62, 0x72, 0x69, 0x6a, 0x2e, 0x76, 0x65, 0x72,
	0x69, 0x66, 0x69, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e,
	0x74, 0x54, 0x79, 0x70, 0x65, 0x48, 0x00, 0x52, 0x0c, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e,
	0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x4c, 0x0a, 0x0e, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e,
	0x74, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x23, 0x2e,
	0x62, 0x72, 0x69, 0x6a, 0x2e, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x72, 0x2e, 0x76, 0x31,
	0x2e, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x54, 0x79,
	0x70, 0x65, 0x48, 0x00, 0x52, 0x0d, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x46, 0x69,
	0x65, 0x6c, 0x64, 0x42, 0x07, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x07, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x24, 0x5a, 0x22, 0x67, 0x6f, 0x2e, 0x62, 0x72, 0x69, 0x6a,
	0x2e, 0x66, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x62, 0x72, 0x69, 0x6a, 0x2f,
	0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_brij_verifier_v1_get_kyc_requirements_proto_rawDescOnce sync.Once
	file_brij_verifier_v1_get_kyc_requirements_proto_rawDescData = file_brij_verifier_v1_get_kyc_requirements_proto_rawDesc
)

func file_brij_verifier_v1_get_kyc_requirements_proto_rawDescGZIP() []byte {
	file_brij_verifier_v1_get_kyc_requirements_proto_rawDescOnce.Do(func() {
		file_brij_verifier_v1_get_kyc_requirements_proto_rawDescData = protoimpl.X.CompressGZIP(file_brij_verifier_v1_get_kyc_requirements_proto_rawDescData)
	})
	return file_brij_verifier_v1_get_kyc_requirements_proto_rawDescData
}

var file_brij_verifier_v1_get_kyc_requirements_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_brij_verifier_v1_get_kyc_requirements_proto_goTypes = []any{
	(*GetKycRequirementsRequest)(nil),  // 0: brij.verifier.v1.GetKycRequirementsRequest
	(*GetKycRequirementsResponse)(nil), // 1: brij.verifier.v1.GetKycRequirementsResponse
	(*Requirement)(nil),                // 2: brij.verifier.v1.Requirement
	(*Formula)(nil),                    // 3: brij.verifier.v1.Formula
	(*Formula_Nested)(nil),             // 4: brij.verifier.v1.Formula.Nested
	(*Formula_Condition)(nil),          // 5: brij.verifier.v1.Formula.Condition
	(DataType)(0),                      // 6: brij.verifier.v1.DataType
	(DocumentType)(0),                  // 7: brij.verifier.v1.DocumentType
	(DocumentFieldType)(0),             // 8: brij.verifier.v1.DocumentFieldType
}
var file_brij_verifier_v1_get_kyc_requirements_proto_depIdxs = []int32{
	2,  // 0: brij.verifier.v1.GetKycRequirementsResponse.requirements:type_name -> brij.verifier.v1.Requirement
	6,  // 1: brij.verifier.v1.Requirement.type:type_name -> brij.verifier.v1.DataType
	3,  // 2: brij.verifier.v1.Requirement.formula:type_name -> brij.verifier.v1.Formula
	4,  // 3: brij.verifier.v1.Formula.and:type_name -> brij.verifier.v1.Formula.Nested
	4,  // 4: brij.verifier.v1.Formula.or:type_name -> brij.verifier.v1.Formula.Nested
	3,  // 5: brij.verifier.v1.Formula.not:type_name -> brij.verifier.v1.Formula
	5,  // 6: brij.verifier.v1.Formula.condition:type_name -> brij.verifier.v1.Formula.Condition
	3,  // 7: brij.verifier.v1.Formula.Nested.formulas:type_name -> brij.verifier.v1.Formula
	7,  // 8: brij.verifier.v1.Formula.Condition.document_type:type_name -> brij.verifier.v1.DocumentType
	8,  // 9: brij.verifier.v1.Formula.Condition.document_field:type_name -> brij.verifier.v1.DocumentFieldType
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_brij_verifier_v1_get_kyc_requirements_proto_init() }
func file_brij_verifier_v1_get_kyc_requirements_proto_init() {
	if File_brij_verifier_v1_get_kyc_requirements_proto != nil {
		return
	}
	file_brij_verifier_v1_data_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_brij_verifier_v1_get_kyc_requirements_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*GetKycRequirementsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_brij_verifier_v1_get_kyc_requirements_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*GetKycRequirementsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_brij_verifier_v1_get_kyc_requirements_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*Requirement); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_brij_verifier_v1_get_kyc_requirements_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*Formula); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_brij_verifier_v1_get_kyc_requirements_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*Formula_Nested); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_brij_verifier_v1_get_kyc_requirements_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*Formula_Condition); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_brij_verifier_v1_get_kyc_requirements_proto_msgTypes[3].OneofWrappers = []any{
		(*Formula_And)(nil),
		(*Formula_Or)(nil),
		(*Formula_Not)(nil),
		(*Formula_Constant)(nil),
		(*Formula_Condition_)(nil),
	}
	file_brij_verifier_v1_get_kyc_requirements_proto_msgTypes[5].OneofWrappers = []any{
		(*Formula_Condition_CountryCode)(nil),
		(*Formula_Condition_DocumentType)(nil),
		(*Formula_Condition_DocumentField)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_brij_verifier_v1_get_kyc_requirements_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_brij_verifier_v1_get_kyc_requirements_proto_goTypes,
		DependencyIndexes: file_brij_verifier_v1_get_kyc_requirements_proto_depIdxs,
		MessageInfos:      file_brij_verifier_v1_get_kyc_requirements_proto_msgTypes,
	}.Build()
	File_brij_verifier_v1_get_kyc_requirements_proto = out.File
	file_brij_verifier_v1_get_kyc_requirements_proto_rawDesc = nil
	file_brij_verifier_v1_get_kyc_requirements_proto_goTypes = nil
	file_brij_verifier_v1_get_kyc_requirements_proto_depIdxs = nil
}
