// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: brij/verifier/v1/get_kyc_requirements.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetKycRequirementsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Country       string                 `protobuf:"bytes,1,opt,name=country,proto3" json:"country,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKycRequirementsRequest) Reset() {
	*x = GetKycRequirementsRequest{}
	mi := &file_brij_verifier_v1_get_kyc_requirements_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKycRequirementsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKycRequirementsRequest) ProtoMessage() {}

func (x *GetKycRequirementsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_brij_verifier_v1_get_kyc_requirements_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKycRequirementsRequest.ProtoReflect.Descriptor instead.
func (*GetKycRequirementsRequest) Descriptor() ([]byte, []int) {
	return file_brij_verifier_v1_get_kyc_requirements_proto_rawDescGZIP(), []int{0}
}

func (x *GetKycRequirementsRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

type GetKycRequirementsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Country       string                 `protobuf:"bytes,1,opt,name=country,proto3" json:"country,omitempty"`
	Requirements  []*Requirement         `protobuf:"bytes,2,rep,name=requirements,proto3" json:"requirements,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKycRequirementsResponse) Reset() {
	*x = GetKycRequirementsResponse{}
	mi := &file_brij_verifier_v1_get_kyc_requirements_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKycRequirementsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKycRequirementsResponse) ProtoMessage() {}

func (x *GetKycRequirementsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_brij_verifier_v1_get_kyc_requirements_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKycRequirementsResponse.ProtoReflect.Descriptor instead.
func (*GetKycRequirementsResponse) Descriptor() ([]byte, []int) {
	return file_brij_verifier_v1_get_kyc_requirements_proto_rawDescGZIP(), []int{1}
}

func (x *GetKycRequirementsResponse) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *GetKycRequirementsResponse) GetRequirements() []*Requirement {
	if x != nil {
		return x.Requirements
	}
	return nil
}

type Requirement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          DataType               `protobuf:"varint,1,opt,name=type,proto3,enum=brij.verifier.v1.DataType" json:"type,omitempty"`
	Formula       *Formula               `protobuf:"bytes,2,opt,name=formula,proto3" json:"formula,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Requirement) Reset() {
	*x = Requirement{}
	mi := &file_brij_verifier_v1_get_kyc_requirements_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Requirement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Requirement) ProtoMessage() {}

func (x *Requirement) ProtoReflect() protoreflect.Message {
	mi := &file_brij_verifier_v1_get_kyc_requirements_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Requirement.ProtoReflect.Descriptor instead.
func (*Requirement) Descriptor() ([]byte, []int) {
	return file_brij_verifier_v1_get_kyc_requirements_proto_rawDescGZIP(), []int{2}
}

func (x *Requirement) GetType() DataType {
	if x != nil {
		return x.Type
	}
	return DataType_DATA_TYPE_UNSPECIFIED
}

func (x *Requirement) GetFormula() *Formula {
	if x != nil {
		return x.Formula
	}
	return nil
}

type Formula struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*Formula_And
	//	*Formula_Or
	//	*Formula_Not
	//	*Formula_Constant
	//	*Formula_Condition_
	Value         isFormula_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Formula) Reset() {
	*x = Formula{}
	mi := &file_brij_verifier_v1_get_kyc_requirements_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Formula) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Formula) ProtoMessage() {}

func (x *Formula) ProtoReflect() protoreflect.Message {
	mi := &file_brij_verifier_v1_get_kyc_requirements_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Formula.ProtoReflect.Descriptor instead.
func (*Formula) Descriptor() ([]byte, []int) {
	return file_brij_verifier_v1_get_kyc_requirements_proto_rawDescGZIP(), []int{3}
}

func (x *Formula) GetValue() isFormula_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Formula) GetAnd() *Formula_Nested {
	if x != nil {
		if x, ok := x.Value.(*Formula_And); ok {
			return x.And
		}
	}
	return nil
}

func (x *Formula) GetOr() *Formula_Nested {
	if x != nil {
		if x, ok := x.Value.(*Formula_Or); ok {
			return x.Or
		}
	}
	return nil
}

func (x *Formula) GetNot() *Formula {
	if x != nil {
		if x, ok := x.Value.(*Formula_Not); ok {
			return x.Not
		}
	}
	return nil
}

func (x *Formula) GetConstant() bool {
	if x != nil {
		if x, ok := x.Value.(*Formula_Constant); ok {
			return x.Constant
		}
	}
	return false
}

func (x *Formula) GetCondition() *Formula_Condition {
	if x != nil {
		if x, ok := x.Value.(*Formula_Condition_); ok {
			return x.Condition
		}
	}
	return nil
}

type isFormula_Value interface {
	isFormula_Value()
}

type Formula_And struct {
	And *Formula_Nested `protobuf:"bytes,1,opt,name=and,proto3,oneof"`
}

type Formula_Or struct {
	Or *Formula_Nested `protobuf:"bytes,2,opt,name=or,proto3,oneof"`
}

type Formula_Not struct {
	Not *Formula `protobuf:"bytes,3,opt,name=not,proto3,oneof"`
}

type Formula_Constant struct {
	Constant bool `protobuf:"varint,4,opt,name=constant,proto3,oneof"`
}

type Formula_Condition_ struct {
	Condition *Formula_Condition `protobuf:"bytes,5,opt,name=condition,proto3,oneof"`
}

func (*Formula_And) isFormula_Value() {}

func (*Formula_Or) isFormula_Value() {}

func (*Formula_Not) isFormula_Value() {}

func (*Formula_Constant) isFormula_Value() {}

func (*Formula_Condition_) isFormula_Value() {}

type Formula_Nested struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Formulas      []*Formula             `protobuf:"bytes,1,rep,name=formulas,proto3" json:"formulas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Formula_Nested) Reset() {
	*x = Formula_Nested{}
	mi := &file_brij_verifier_v1_get_kyc_requirements_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Formula_Nested) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Formula_Nested) ProtoMessage() {}

func (x *Formula_Nested) ProtoReflect() protoreflect.Message {
	mi := &file_brij_verifier_v1_get_kyc_requirements_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Formula_Nested.ProtoReflect.Descriptor instead.
func (*Formula_Nested) Descriptor() ([]byte, []int) {
	return file_brij_verifier_v1_get_kyc_requirements_proto_rawDescGZIP(), []int{3, 0}
}

func (x *Formula_Nested) GetFormulas() []*Formula {
	if x != nil {
		return x.Formulas
	}
	return nil
}

type Formula_Condition struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*Formula_Condition_CountryCode
	//	*Formula_Condition_DocumentType
	//	*Formula_Condition_DocumentField
	Value         isFormula_Condition_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Formula_Condition) Reset() {
	*x = Formula_Condition{}
	mi := &file_brij_verifier_v1_get_kyc_requirements_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Formula_Condition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Formula_Condition) ProtoMessage() {}

func (x *Formula_Condition) ProtoReflect() protoreflect.Message {
	mi := &file_brij_verifier_v1_get_kyc_requirements_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Formula_Condition.ProtoReflect.Descriptor instead.
func (*Formula_Condition) Descriptor() ([]byte, []int) {
	return file_brij_verifier_v1_get_kyc_requirements_proto_rawDescGZIP(), []int{3, 1}
}

func (x *Formula_Condition) GetValue() isFormula_Condition_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Formula_Condition) GetCountryCode() string {
	if x != nil {
		if x, ok := x.Value.(*Formula_Condition_CountryCode); ok {
			return x.CountryCode
		}
	}
	return ""
}

func (x *Formula_Condition) GetDocumentType() DocumentType {
	if x != nil {
		if x, ok := x.Value.(*Formula_Condition_DocumentType); ok {
			return x.DocumentType
		}
	}
	return DocumentType_DOCUMENT_TYPE_UNSPECIFIED
}

func (x *Formula_Condition) GetDocumentField() DocumentFieldType {
	if x != nil {
		if x, ok := x.Value.(*Formula_Condition_DocumentField); ok {
			return x.DocumentField
		}
	}
	return DocumentFieldType_DOCUMENT_FIELD_TYPE_UNSPECIFIED
}

type isFormula_Condition_Value interface {
	isFormula_Condition_Value()
}

type Formula_Condition_CountryCode struct {
	CountryCode string `protobuf:"bytes,1,opt,name=country_code,json=countryCode,proto3,oneof"`
}

type Formula_Condition_DocumentType struct {
	DocumentType DocumentType `protobuf:"varint,2,opt,name=document_type,json=documentType,proto3,enum=brij.verifier.v1.DocumentType,oneof"`
}

type Formula_Condition_DocumentField struct {
	DocumentField DocumentFieldType `protobuf:"varint,3,opt,name=document_field,json=documentField,proto3,enum=brij.verifier.v1.DocumentFieldType,oneof"`
}

func (*Formula_Condition_CountryCode) isFormula_Condition_Value() {}

func (*Formula_Condition_DocumentType) isFormula_Condition_Value() {}

func (*Formula_Condition_DocumentField) isFormula_Condition_Value() {}

var File_brij_verifier_v1_get_kyc_requirements_proto protoreflect.FileDescriptor

const file_brij_verifier_v1_get_kyc_requirements_proto_rawDesc = "" +
	"\n" +
	"+brij/verifier/v1/get_kyc_requirements.proto\x12\x10brij.verifier.v1\x1a\x1bbrij/verifier/v1/data.proto\"5\n" +
	"\x19GetKycRequirementsRequest\x12\x18\n" +
	"\acountry\x18\x01 \x01(\tR\acountry\"y\n" +
	"\x1aGetKycRequirementsResponse\x12\x18\n" +
	"\acountry\x18\x01 \x01(\tR\acountry\x12A\n" +
	"\frequirements\x18\x02 \x03(\v2\x1d.brij.verifier.v1.RequirementR\frequirements\"r\n" +
	"\vRequirement\x12.\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1a.brij.verifier.v1.DataTypeR\x04type\x123\n" +
	"\aformula\x18\x02 \x01(\v2\x19.brij.verifier.v1.FormulaR\aformula\"\xa0\x04\n" +
	"\aFormula\x124\n" +
	"\x03and\x18\x01 \x01(\v2 .brij.verifier.v1.Formula.NestedH\x00R\x03and\x122\n" +
	"\x02or\x18\x02 \x01(\v2 .brij.verifier.v1.Formula.NestedH\x00R\x02or\x12-\n" +
	"\x03not\x18\x03 \x01(\v2\x19.brij.verifier.v1.FormulaH\x00R\x03not\x12\x1c\n" +
	"\bconstant\x18\x04 \x01(\bH\x00R\bconstant\x12C\n" +
	"\tcondition\x18\x05 \x01(\v2#.brij.verifier.v1.Formula.ConditionH\x00R\tcondition\x1a?\n" +
	"\x06Nested\x125\n" +
	"\bformulas\x18\x01 \x03(\v2\x19.brij.verifier.v1.FormulaR\bformulas\x1a\xce\x01\n" +
	"\tCondition\x12#\n" +
	"\fcountry_code\x18\x01 \x01(\tH\x00R\vcountryCode\x12E\n" +
	"\rdocument_type\x18\x02 \x01(\x0e2\x1e.brij.verifier.v1.DocumentTypeH\x00R\fdocumentType\x12L\n" +
	"\x0edocument_field\x18\x03 \x01(\x0e2#.brij.verifier.v1.DocumentFieldTypeH\x00R\rdocumentFieldB\a\n" +
	"\x05valueB\a\n" +
	"\x05valueB$Z\"go.brij.fi/protos/brij/verifier/v1b\x06proto3"

var (
	file_brij_verifier_v1_get_kyc_requirements_proto_rawDescOnce sync.Once
	file_brij_verifier_v1_get_kyc_requirements_proto_rawDescData []byte
)

func file_brij_verifier_v1_get_kyc_requirements_proto_rawDescGZIP() []byte {
	file_brij_verifier_v1_get_kyc_requirements_proto_rawDescOnce.Do(func() {
		file_brij_verifier_v1_get_kyc_requirements_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_brij_verifier_v1_get_kyc_requirements_proto_rawDesc), len(file_brij_verifier_v1_get_kyc_requirements_proto_rawDesc)))
	})
	return file_brij_verifier_v1_get_kyc_requirements_proto_rawDescData
}

var file_brij_verifier_v1_get_kyc_requirements_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_brij_verifier_v1_get_kyc_requirements_proto_goTypes = []any{
	(*GetKycRequirementsRequest)(nil),  // 0: brij.verifier.v1.GetKycRequirementsRequest
	(*GetKycRequirementsResponse)(nil), // 1: brij.verifier.v1.GetKycRequirementsResponse
	(*Requirement)(nil),                // 2: brij.verifier.v1.Requirement
	(*Formula)(nil),                    // 3: brij.verifier.v1.Formula
	(*Formula_Nested)(nil),             // 4: brij.verifier.v1.Formula.Nested
	(*Formula_Condition)(nil),          // 5: brij.verifier.v1.Formula.Condition
	(DataType)(0),                      // 6: brij.verifier.v1.DataType
	(DocumentType)(0),                  // 7: brij.verifier.v1.DocumentType
	(DocumentFieldType)(0),             // 8: brij.verifier.v1.DocumentFieldType
}
var file_brij_verifier_v1_get_kyc_requirements_proto_depIdxs = []int32{
	2,  // 0: brij.verifier.v1.GetKycRequirementsResponse.requirements:type_name -> brij.verifier.v1.Requirement
	6,  // 1: brij.verifier.v1.Requirement.type:type_name -> brij.verifier.v1.DataType
	3,  // 2: brij.verifier.v1.Requirement.formula:type_name -> brij.verifier.v1.Formula
	4,  // 3: brij.verifier.v1.Formula.and:type_name -> brij.verifier.v1.Formula.Nested
	4,  // 4: brij.verifier.v1.Formula.or:type_name -> brij.verifier.v1.Formula.Nested
	3,  // 5: brij.verifier.v1.Formula.not:type_name -> brij.verifier.v1.Formula
	5,  // 6: brij.verifier.v1.Formula.condition:type_name -> brij.verifier.v1.Formula.Condition
	3,  // 7: brij.verifier.v1.Formula.Nested.formulas:type_name -> brij.verifier.v1.Formula
	7,  // 8: brij.verifier.v1.Formula.Condition.document_type:type_name -> brij.verifier.v1.DocumentType
	8,  // 9: brij.verifier.v1.Formula.Condition.document_field:type_name -> brij.verifier.v1.DocumentFieldType
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_brij_verifier_v1_get_kyc_requirements_proto_init() }
func file_brij_verifier_v1_get_kyc_requirements_proto_init() {
	if File_brij_verifier_v1_get_kyc_requirements_proto != nil {
		return
	}
	file_brij_verifier_v1_data_proto_init()
	file_brij_verifier_v1_get_kyc_requirements_proto_msgTypes[3].OneofWrappers = []any{
		(*Formula_And)(nil),
		(*Formula_Or)(nil),
		(*Formula_Not)(nil),
		(*Formula_Constant)(nil),
		(*Formula_Condition_)(nil),
	}
	file_brij_verifier_v1_get_kyc_requirements_proto_msgTypes[5].OneofWrappers = []any{
		(*Formula_Condition_CountryCode)(nil),
		(*Formula_Condition_DocumentType)(nil),
		(*Formula_Condition_DocumentField)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_brij_verifier_v1_get_kyc_requirements_proto_rawDesc), len(file_brij_verifier_v1_get_kyc_requirements_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_brij_verifier_v1_get_kyc_requirements_proto_goTypes,
		DependencyIndexes: file_brij_verifier_v1_get_kyc_requirements_proto_depIdxs,
		MessageInfos:      file_brij_verifier_v1_get_kyc_requirements_proto_msgTypes,
	}.Build()
	File_brij_verifier_v1_get_kyc_requirements_proto = out.File
	file_brij_verifier_v1_get_kyc_requirements_proto_goTypes = nil
	file_brij_verifier_v1_get_kyc_requirements_proto_depIdxs = nil
}
