// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: brij/verifier/v1/service.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_brij_verifier_v1_service_proto protoreflect.FileDescriptor

const file_brij_verifier_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x1ebrij/verifier/v1/service.proto\x12\x10brij.verifier.v1\x1a+brij/verifier/v1/get_kyc_requirements.proto\x1a,brij/verifier/v1/init_email_validation.proto\x1a,brij/verifier/v1/init_phone_validation.proto\x1a brij/verifier/v1/start_kyc.proto\x1a%brij/verifier/v1/validate_email.proto\x1a%brij/verifier/v1/validate_phone.proto\x1a\x1cgoogle/api/annotations.proto2\xb2\x06\n" +
	"\x0fVerifierService\x12\x93\x01\n" +
	"\x13InitEmailValidation\x12,.brij.verifier.v1.InitEmailValidationRequest\x1a-.brij.verifier.v1.InitEmailValidationResponse\"\x1f\x82\xd3\xe4\x93\x02\x19\"\x17/v1/initEmailValidation\x12{\n" +
	"\rValidateEmail\x12&.brij.verifier.v1.ValidateEmailRequest\x1a'.brij.verifier.v1.ValidateEmailResponse\"\x19\x82\xd3\xe4\x93\x02\x13\"\x11/v1/validateEmail\x12\x93\x01\n" +
	"\x13InitPhoneValidation\x12,.brij.verifier.v1.InitPhoneValidationRequest\x1a-.brij.verifier.v1.InitPhoneValidationResponse\"\x1f\x82\xd3\xe4\x93\x02\x19\"\x17/v1/initPhoneValidation\x12{\n" +
	"\rValidatePhone\x12&.brij.verifier.v1.ValidatePhoneRequest\x1a'.brij.verifier.v1.ValidatePhoneResponse\"\x19\x82\xd3\xe4\x93\x02\x13\"\x11/v1/validatePhone\x12g\n" +
	"\bStartKyc\x12!.brij.verifier.v1.StartKycRequest\x1a\".brij.verifier.v1.StartKycResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\"\f/v1/startKyc\x12\x8f\x01\n" +
	"\x12GetKycRequirements\x12+.brij.verifier.v1.GetKycRequirementsRequest\x1a,.brij.verifier.v1.GetKycRequirementsResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\"\x16/v1/getKycRequirementsB$Z\"go.brij.fi/protos/brij/verifier/v1b\x06proto3"

var file_brij_verifier_v1_service_proto_goTypes = []any{
	(*InitEmailValidationRequest)(nil),  // 0: brij.verifier.v1.InitEmailValidationRequest
	(*ValidateEmailRequest)(nil),        // 1: brij.verifier.v1.ValidateEmailRequest
	(*InitPhoneValidationRequest)(nil),  // 2: brij.verifier.v1.InitPhoneValidationRequest
	(*ValidatePhoneRequest)(nil),        // 3: brij.verifier.v1.ValidatePhoneRequest
	(*StartKycRequest)(nil),             // 4: brij.verifier.v1.StartKycRequest
	(*GetKycRequirementsRequest)(nil),   // 5: brij.verifier.v1.GetKycRequirementsRequest
	(*InitEmailValidationResponse)(nil), // 6: brij.verifier.v1.InitEmailValidationResponse
	(*ValidateEmailResponse)(nil),       // 7: brij.verifier.v1.ValidateEmailResponse
	(*InitPhoneValidationResponse)(nil), // 8: brij.verifier.v1.InitPhoneValidationResponse
	(*ValidatePhoneResponse)(nil),       // 9: brij.verifier.v1.ValidatePhoneResponse
	(*StartKycResponse)(nil),            // 10: brij.verifier.v1.StartKycResponse
	(*GetKycRequirementsResponse)(nil),  // 11: brij.verifier.v1.GetKycRequirementsResponse
}
var file_brij_verifier_v1_service_proto_depIdxs = []int32{
	0,  // 0: brij.verifier.v1.VerifierService.InitEmailValidation:input_type -> brij.verifier.v1.InitEmailValidationRequest
	1,  // 1: brij.verifier.v1.VerifierService.ValidateEmail:input_type -> brij.verifier.v1.ValidateEmailRequest
	2,  // 2: brij.verifier.v1.VerifierService.InitPhoneValidation:input_type -> brij.verifier.v1.InitPhoneValidationRequest
	3,  // 3: brij.verifier.v1.VerifierService.ValidatePhone:input_type -> brij.verifier.v1.ValidatePhoneRequest
	4,  // 4: brij.verifier.v1.VerifierService.StartKyc:input_type -> brij.verifier.v1.StartKycRequest
	5,  // 5: brij.verifier.v1.VerifierService.GetKycRequirements:input_type -> brij.verifier.v1.GetKycRequirementsRequest
	6,  // 6: brij.verifier.v1.VerifierService.InitEmailValidation:output_type -> brij.verifier.v1.InitEmailValidationResponse
	7,  // 7: brij.verifier.v1.VerifierService.ValidateEmail:output_type -> brij.verifier.v1.ValidateEmailResponse
	8,  // 8: brij.verifier.v1.VerifierService.InitPhoneValidation:output_type -> brij.verifier.v1.InitPhoneValidationResponse
	9,  // 9: brij.verifier.v1.VerifierService.ValidatePhone:output_type -> brij.verifier.v1.ValidatePhoneResponse
	10, // 10: brij.verifier.v1.VerifierService.StartKyc:output_type -> brij.verifier.v1.StartKycResponse
	11, // 11: brij.verifier.v1.VerifierService.GetKycRequirements:output_type -> brij.verifier.v1.GetKycRequirementsResponse
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_brij_verifier_v1_service_proto_init() }
func file_brij_verifier_v1_service_proto_init() {
	if File_brij_verifier_v1_service_proto != nil {
		return
	}
	file_brij_verifier_v1_get_kyc_requirements_proto_init()
	file_brij_verifier_v1_init_email_validation_proto_init()
	file_brij_verifier_v1_init_phone_validation_proto_init()
	file_brij_verifier_v1_start_kyc_proto_init()
	file_brij_verifier_v1_validate_email_proto_init()
	file_brij_verifier_v1_validate_phone_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_brij_verifier_v1_service_proto_rawDesc), len(file_brij_verifier_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_brij_verifier_v1_service_proto_goTypes,
		DependencyIndexes: file_brij_verifier_v1_service_proto_depIdxs,
	}.Build()
	File_brij_verifier_v1_service_proto = out.File
	file_brij_verifier_v1_service_proto_goTypes = nil
	file_brij_verifier_v1_service_proto_depIdxs = nil
}
