// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: brij/verifier/v1/start_kyc.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartKycRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Country       string                 `protobuf:"bytes,1,opt,name=country,proto3" json:"country,omitempty"`
	DataHashes    []string               `protobuf:"bytes,2,rep,name=data_hashes,json=dataHashes,proto3" json:"data_hashes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartKycRequest) Reset() {
	*x = StartKycRequest{}
	mi := &file_brij_verifier_v1_start_kyc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartKycRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartKycRequest) ProtoMessage() {}

func (x *StartKycRequest) ProtoReflect() protoreflect.Message {
	mi := &file_brij_verifier_v1_start_kyc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartKycRequest.ProtoReflect.Descriptor instead.
func (*StartKycRequest) Descriptor() ([]byte, []int) {
	return file_brij_verifier_v1_start_kyc_proto_rawDescGZIP(), []int{0}
}

func (x *StartKycRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *StartKycRequest) GetDataHashes() []string {
	if x != nil {
		return x.DataHashes
	}
	return nil
}

type StartKycResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KycId         string                 `protobuf:"bytes,1,opt,name=kyc_id,json=kycId,proto3" json:"kyc_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartKycResponse) Reset() {
	*x = StartKycResponse{}
	mi := &file_brij_verifier_v1_start_kyc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartKycResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartKycResponse) ProtoMessage() {}

func (x *StartKycResponse) ProtoReflect() protoreflect.Message {
	mi := &file_brij_verifier_v1_start_kyc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartKycResponse.ProtoReflect.Descriptor instead.
func (*StartKycResponse) Descriptor() ([]byte, []int) {
	return file_brij_verifier_v1_start_kyc_proto_rawDescGZIP(), []int{1}
}

func (x *StartKycResponse) GetKycId() string {
	if x != nil {
		return x.KycId
	}
	return ""
}

var File_brij_verifier_v1_start_kyc_proto protoreflect.FileDescriptor

const file_brij_verifier_v1_start_kyc_proto_rawDesc = "" +
	"\n" +
	" brij/verifier/v1/start_kyc.proto\x12\x10brij.verifier.v1\"L\n" +
	"\x0fStartKycRequest\x12\x18\n" +
	"\acountry\x18\x01 \x01(\tR\acountry\x12\x1f\n" +
	"\vdata_hashes\x18\x02 \x03(\tR\n" +
	"dataHashes\")\n" +
	"\x10StartKycResponse\x12\x15\n" +
	"\x06kyc_id\x18\x01 \x01(\tR\x05kycIdB$Z\"go.brij.fi/protos/brij/verifier/v1b\x06proto3"

var (
	file_brij_verifier_v1_start_kyc_proto_rawDescOnce sync.Once
	file_brij_verifier_v1_start_kyc_proto_rawDescData []byte
)

func file_brij_verifier_v1_start_kyc_proto_rawDescGZIP() []byte {
	file_brij_verifier_v1_start_kyc_proto_rawDescOnce.Do(func() {
		file_brij_verifier_v1_start_kyc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_brij_verifier_v1_start_kyc_proto_rawDesc), len(file_brij_verifier_v1_start_kyc_proto_rawDesc)))
	})
	return file_brij_verifier_v1_start_kyc_proto_rawDescData
}

var file_brij_verifier_v1_start_kyc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_brij_verifier_v1_start_kyc_proto_goTypes = []any{
	(*StartKycRequest)(nil),  // 0: brij.verifier.v1.StartKycRequest
	(*StartKycResponse)(nil), // 1: brij.verifier.v1.StartKycResponse
}
var file_brij_verifier_v1_start_kyc_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_brij_verifier_v1_start_kyc_proto_init() }
func file_brij_verifier_v1_start_kyc_proto_init() {
	if File_brij_verifier_v1_start_kyc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_brij_verifier_v1_start_kyc_proto_rawDesc), len(file_brij_verifier_v1_start_kyc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_brij_verifier_v1_start_kyc_proto_goTypes,
		DependencyIndexes: file_brij_verifier_v1_start_kyc_proto_depIdxs,
		MessageInfos:      file_brij_verifier_v1_start_kyc_proto_msgTypes,
	}.Build()
	File_brij_verifier_v1_start_kyc_proto = out.File
	file_brij_verifier_v1_start_kyc_proto_goTypes = nil
	file_brij_verifier_v1_start_kyc_proto_depIdxs = nil
}
