// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: brij/verifier/v1/start_kyc.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartKycRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Country    string   `protobuf:"bytes,1,opt,name=country,proto3" json:"country,omitempty"`
	DataHashes []string `protobuf:"bytes,2,rep,name=data_hashes,json=dataHashes,proto3" json:"data_hashes,omitempty"`
}

func (x *StartKycRequest) Reset() {
	*x = StartKycRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_brij_verifier_v1_start_kyc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartKycRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartKycRequest) ProtoMessage() {}

func (x *StartKycRequest) ProtoReflect() protoreflect.Message {
	mi := &file_brij_verifier_v1_start_kyc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartKycRequest.ProtoReflect.Descriptor instead.
func (*StartKycRequest) Descriptor() ([]byte, []int) {
	return file_brij_verifier_v1_start_kyc_proto_rawDescGZIP(), []int{0}
}

func (x *StartKycRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *StartKycRequest) GetDataHashes() []string {
	if x != nil {
		return x.DataHashes
	}
	return nil
}

type StartKycResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KycId string `protobuf:"bytes,1,opt,name=kyc_id,json=kycId,proto3" json:"kyc_id,omitempty"`
}

func (x *StartKycResponse) Reset() {
	*x = StartKycResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_brij_verifier_v1_start_kyc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartKycResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartKycResponse) ProtoMessage() {}

func (x *StartKycResponse) ProtoReflect() protoreflect.Message {
	mi := &file_brij_verifier_v1_start_kyc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartKycResponse.ProtoReflect.Descriptor instead.
func (*StartKycResponse) Descriptor() ([]byte, []int) {
	return file_brij_verifier_v1_start_kyc_proto_rawDescGZIP(), []int{1}
}

func (x *StartKycResponse) GetKycId() string {
	if x != nil {
		return x.KycId
	}
	return ""
}

var File_brij_verifier_v1_start_kyc_proto protoreflect.FileDescriptor

var file_brij_verifier_v1_start_kyc_proto_rawDesc = []byte{
	0x0a, 0x20, 0x62, 0x72, 0x69, 0x6a, 0x2f, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x72, 0x2f,
	0x76, 0x31, 0x2f, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x6b, 0x79, 0x63, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x10, 0x62, 0x72, 0x69, 0x6a, 0x2e, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65,
	0x72, 0x2e, 0x76, 0x31, 0x22, 0x4c, 0x0a, 0x0f, 0x53, 0x74, 0x61, 0x72, 0x74, 0x4b, 0x79, 0x63,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72,
	0x79, 0x12, 0x1f, 0x0a, 0x0b, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x65, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x61, 0x74, 0x61, 0x48, 0x61, 0x73, 0x68,
	0x65, 0x73, 0x22, 0x29, 0x0a, 0x10, 0x53, 0x74, 0x61, 0x72, 0x74, 0x4b, 0x79, 0x63, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x6b, 0x79, 0x63, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6b, 0x79, 0x63, 0x49, 0x64, 0x42, 0x24, 0x5a,
	0x22, 0x67, 0x6f, 0x2e, 0x62, 0x72, 0x69, 0x6a, 0x2e, 0x66, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x73, 0x2f, 0x62, 0x72, 0x69, 0x6a, 0x2f, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x72,
	0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_brij_verifier_v1_start_kyc_proto_rawDescOnce sync.Once
	file_brij_verifier_v1_start_kyc_proto_rawDescData = file_brij_verifier_v1_start_kyc_proto_rawDesc
)

func file_brij_verifier_v1_start_kyc_proto_rawDescGZIP() []byte {
	file_brij_verifier_v1_start_kyc_proto_rawDescOnce.Do(func() {
		file_brij_verifier_v1_start_kyc_proto_rawDescData = protoimpl.X.CompressGZIP(file_brij_verifier_v1_start_kyc_proto_rawDescData)
	})
	return file_brij_verifier_v1_start_kyc_proto_rawDescData
}

var file_brij_verifier_v1_start_kyc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_brij_verifier_v1_start_kyc_proto_goTypes = []any{
	(*StartKycRequest)(nil),  // 0: brij.verifier.v1.StartKycRequest
	(*StartKycResponse)(nil), // 1: brij.verifier.v1.StartKycResponse
}
var file_brij_verifier_v1_start_kyc_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_brij_verifier_v1_start_kyc_proto_init() }
func file_brij_verifier_v1_start_kyc_proto_init() {
	if File_brij_verifier_v1_start_kyc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_brij_verifier_v1_start_kyc_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*StartKycRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_brij_verifier_v1_start_kyc_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*StartKycResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_brij_verifier_v1_start_kyc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_brij_verifier_v1_start_kyc_proto_goTypes,
		DependencyIndexes: file_brij_verifier_v1_start_kyc_proto_depIdxs,
		MessageInfos:      file_brij_verifier_v1_start_kyc_proto_msgTypes,
	}.Build()
	File_brij_verifier_v1_start_kyc_proto = out.File
	file_brij_verifier_v1_start_kyc_proto_rawDesc = nil
	file_brij_verifier_v1_start_kyc_proto_goTypes = nil
	file_brij_verifier_v1_start_kyc_proto_depIdxs = nil
}
