// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: brij/verifier/v1/validate_email.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ValidateEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	DataId        string                 `protobuf:"bytes,2,opt,name=data_id,json=dataId,proto3" json:"data_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateEmailRequest) Reset() {
	*x = ValidateEmailRequest{}
	mi := &file_brij_verifier_v1_validate_email_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateEmailRequest) ProtoMessage() {}

func (x *ValidateEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_brij_verifier_v1_validate_email_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateEmailRequest.ProtoReflect.Descriptor instead.
func (*ValidateEmailRequest) Descriptor() ([]byte, []int) {
	return file_brij_verifier_v1_validate_email_proto_rawDescGZIP(), []int{0}
}

func (x *ValidateEmailRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ValidateEmailRequest) GetDataId() string {
	if x != nil {
		return x.DataId
	}
	return ""
}

type ValidateEmailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateEmailResponse) Reset() {
	*x = ValidateEmailResponse{}
	mi := &file_brij_verifier_v1_validate_email_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateEmailResponse) ProtoMessage() {}

func (x *ValidateEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_brij_verifier_v1_validate_email_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateEmailResponse.ProtoReflect.Descriptor instead.
func (*ValidateEmailResponse) Descriptor() ([]byte, []int) {
	return file_brij_verifier_v1_validate_email_proto_rawDescGZIP(), []int{1}
}

var File_brij_verifier_v1_validate_email_proto protoreflect.FileDescriptor

const file_brij_verifier_v1_validate_email_proto_rawDesc = "" +
	"\n" +
	"%brij/verifier/v1/validate_email.proto\x12\x10brij.verifier.v1\"C\n" +
	"\x14ValidateEmailRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x17\n" +
	"\adata_id\x18\x02 \x01(\tR\x06dataId\"\x17\n" +
	"\x15ValidateEmailResponseB$Z\"go.brij.fi/protos/brij/verifier/v1b\x06proto3"

var (
	file_brij_verifier_v1_validate_email_proto_rawDescOnce sync.Once
	file_brij_verifier_v1_validate_email_proto_rawDescData []byte
)

func file_brij_verifier_v1_validate_email_proto_rawDescGZIP() []byte {
	file_brij_verifier_v1_validate_email_proto_rawDescOnce.Do(func() {
		file_brij_verifier_v1_validate_email_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_brij_verifier_v1_validate_email_proto_rawDesc), len(file_brij_verifier_v1_validate_email_proto_rawDesc)))
	})
	return file_brij_verifier_v1_validate_email_proto_rawDescData
}

var file_brij_verifier_v1_validate_email_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_brij_verifier_v1_validate_email_proto_goTypes = []any{
	(*ValidateEmailRequest)(nil),  // 0: brij.verifier.v1.ValidateEmailRequest
	(*ValidateEmailResponse)(nil), // 1: brij.verifier.v1.ValidateEmailResponse
}
var file_brij_verifier_v1_validate_email_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_brij_verifier_v1_validate_email_proto_init() }
func file_brij_verifier_v1_validate_email_proto_init() {
	if File_brij_verifier_v1_validate_email_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_brij_verifier_v1_validate_email_proto_rawDesc), len(file_brij_verifier_v1_validate_email_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_brij_verifier_v1_validate_email_proto_goTypes,
		DependencyIndexes: file_brij_verifier_v1_validate_email_proto_depIdxs,
		MessageInfos:      file_brij_verifier_v1_validate_email_proto_msgTypes,
	}.Build()
	File_brij_verifier_v1_validate_email_proto = out.File
	file_brij_verifier_v1_validate_email_proto_goTypes = nil
	file_brij_verifier_v1_validate_email_proto_depIdxs = nil
}
