// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: brij/storage/v1/partner/service.proto

package partner

import (
	common "go.brij.fi/protos/brij/storage/v1/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicKey     string                 `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInfoRequest) Reset() {
	*x = GetInfoRequest{}
	mi := &file_brij_storage_v1_partner_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoRequest) ProtoMessage() {}

func (x *GetInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_brij_storage_v1_partner_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoRequest.ProtoReflect.Descriptor instead.
func (*GetInfoRequest) Descriptor() ([]byte, []int) {
	return file_brij_storage_v1_partner_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetInfoRequest) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

type GetInfoResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	EncryptedSecretKey string                 `protobuf:"bytes,1,opt,name=encrypted_secret_key,json=encryptedSecretKey,proto3" json:"encrypted_secret_key,omitempty"`
	PublicKey          string                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	WalletAddress      string                 `protobuf:"bytes,3,opt,name=wallet_address,json=walletAddress,proto3" json:"wallet_address,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetInfoResponse) Reset() {
	*x = GetInfoResponse{}
	mi := &file_brij_storage_v1_partner_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoResponse) ProtoMessage() {}

func (x *GetInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_brij_storage_v1_partner_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoResponse.ProtoReflect.Descriptor instead.
func (*GetInfoResponse) Descriptor() ([]byte, []int) {
	return file_brij_storage_v1_partner_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetInfoResponse) GetEncryptedSecretKey() string {
	if x != nil {
		return x.EncryptedSecretKey
	}
	return ""
}

func (x *GetInfoResponse) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *GetInfoResponse) GetWalletAddress() string {
	if x != nil {
		return x.WalletAddress
	}
	return ""
}

type GetUserDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserPublicKey string                 `protobuf:"bytes,1,opt,name=user_public_key,json=userPublicKey,proto3" json:"user_public_key,omitempty"`
	IncludeValues bool                   `protobuf:"varint,2,opt,name=include_values,json=includeValues,proto3" json:"include_values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserDataRequest) Reset() {
	*x = GetUserDataRequest{}
	mi := &file_brij_storage_v1_partner_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserDataRequest) ProtoMessage() {}

func (x *GetUserDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_brij_storage_v1_partner_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserDataRequest.ProtoReflect.Descriptor instead.
func (*GetUserDataRequest) Descriptor() ([]byte, []int) {
	return file_brij_storage_v1_partner_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserDataRequest) GetUserPublicKey() string {
	if x != nil {
		return x.UserPublicKey
	}
	return ""
}

func (x *GetUserDataRequest) GetIncludeValues() bool {
	if x != nil {
		return x.IncludeValues
	}
	return false
}

type GetUserDataResponse struct {
	state          protoimpl.MessageState        `protogen:"open.v1"`
	UserData       []*common.UserDataField       `protobuf:"bytes,1,rep,name=user_data,json=userData,proto3" json:"user_data,omitempty"`
	ValidationData []*common.ValidationDataField `protobuf:"bytes,2,rep,name=validation_data,json=validationData,proto3" json:"validation_data,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetUserDataResponse) Reset() {
	*x = GetUserDataResponse{}
	mi := &file_brij_storage_v1_partner_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserDataResponse) ProtoMessage() {}

func (x *GetUserDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_brij_storage_v1_partner_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserDataResponse.ProtoReflect.Descriptor instead.
func (*GetUserDataResponse) Descriptor() ([]byte, []int) {
	return file_brij_storage_v1_partner_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserDataResponse) GetUserData() []*common.UserDataField {
	if x != nil {
		return x.UserData
	}
	return nil
}

func (x *GetUserDataResponse) GetValidationData() []*common.ValidationDataField {
	if x != nil {
		return x.ValidationData
	}
	return nil
}

type SetValidationDataRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ValidationDataEnvelope
	Payload       []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Signature     []byte `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetValidationDataRequest) Reset() {
	*x = SetValidationDataRequest{}
	mi := &file_brij_storage_v1_partner_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetValidationDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetValidationDataRequest) ProtoMessage() {}

func (x *SetValidationDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_brij_storage_v1_partner_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetValidationDataRequest.ProtoReflect.Descriptor instead.
func (*SetValidationDataRequest) Descriptor() ([]byte, []int) {
	return file_brij_storage_v1_partner_service_proto_rawDescGZIP(), []int{4}
}

func (x *SetValidationDataRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SetValidationDataRequest) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type SetValidationDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetValidationDataResponse) Reset() {
	*x = SetValidationDataResponse{}
	mi := &file_brij_storage_v1_partner_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetValidationDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetValidationDataResponse) ProtoMessage() {}

func (x *SetValidationDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_brij_storage_v1_partner_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetValidationDataResponse.ProtoReflect.Descriptor instead.
func (*SetValidationDataResponse) Descriptor() ([]byte, []int) {
	return file_brij_storage_v1_partner_service_proto_rawDescGZIP(), []int{5}
}

type RemoveValidationDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DataHash      string                 `protobuf:"bytes,1,opt,name=data_hash,json=dataHash,proto3" json:"data_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveValidationDataRequest) Reset() {
	*x = RemoveValidationDataRequest{}
	mi := &file_brij_storage_v1_partner_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveValidationDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveValidationDataRequest) ProtoMessage() {}

func (x *RemoveValidationDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_brij_storage_v1_partner_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveValidationDataRequest.ProtoReflect.Descriptor instead.
func (*RemoveValidationDataRequest) Descriptor() ([]byte, []int) {
	return file_brij_storage_v1_partner_service_proto_rawDescGZIP(), []int{6}
}

func (x *RemoveValidationDataRequest) GetDataHash() string {
	if x != nil {
		return x.DataHash
	}
	return ""
}

type RemoveValidationDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveValidationDataResponse) Reset() {
	*x = RemoveValidationDataResponse{}
	mi := &file_brij_storage_v1_partner_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveValidationDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveValidationDataResponse) ProtoMessage() {}

func (x *RemoveValidationDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_brij_storage_v1_partner_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveValidationDataResponse.ProtoReflect.Descriptor instead.
func (*RemoveValidationDataResponse) Descriptor() ([]byte, []int) {
	return file_brij_storage_v1_partner_service_proto_rawDescGZIP(), []int{7}
}

type GetKycStatusRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Country            string                 `protobuf:"bytes,1,opt,name=country,proto3" json:"country,omitempty"`
	ValidatorPublicKey string                 `protobuf:"bytes,2,opt,name=validator_public_key,json=validatorPublicKey,proto3" json:"validator_public_key,omitempty"`
	UserPublicKey      string                 `protobuf:"bytes,3,opt,name=user_public_key,json=userPublicKey,proto3" json:"user_public_key,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetKycStatusRequest) Reset() {
	*x = GetKycStatusRequest{}
	mi := &file_brij_storage_v1_partner_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKycStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKycStatusRequest) ProtoMessage() {}

func (x *GetKycStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_brij_storage_v1_partner_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKycStatusRequest.ProtoReflect.Descriptor instead.
func (*GetKycStatusRequest) Descriptor() ([]byte, []int) {
	return file_brij_storage_v1_partner_service_proto_rawDescGZIP(), []int{8}
}

func (x *GetKycStatusRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *GetKycStatusRequest) GetValidatorPublicKey() string {
	if x != nil {
		return x.ValidatorPublicKey
	}
	return ""
}

func (x *GetKycStatusRequest) GetUserPublicKey() string {
	if x != nil {
		return x.UserPublicKey
	}
	return ""
}

type GetKycStatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// KycEnvelope
	Payload       []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Signature     []byte `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKycStatusResponse) Reset() {
	*x = GetKycStatusResponse{}
	mi := &file_brij_storage_v1_partner_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKycStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKycStatusResponse) ProtoMessage() {}

func (x *GetKycStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_brij_storage_v1_partner_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKycStatusResponse.ProtoReflect.Descriptor instead.
func (*GetKycStatusResponse) Descriptor() ([]byte, []int) {
	return file_brij_storage_v1_partner_service_proto_rawDescGZIP(), []int{9}
}

func (x *GetKycStatusResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *GetKycStatusResponse) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type CreateKycStatusRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// KycEnvelope
	Payload       []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Signature     []byte `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateKycStatusRequest) Reset() {
	*x = CreateKycStatusRequest{}
	mi := &file_brij_storage_v1_partner_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateKycStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateKycStatusRequest) ProtoMessage() {}

func (x *CreateKycStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_brij_storage_v1_partner_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateKycStatusRequest.ProtoReflect.Descriptor instead.
func (*CreateKycStatusRequest) Descriptor() ([]byte, []int) {
	return file_brij_storage_v1_partner_service_proto_rawDescGZIP(), []int{10}
}

func (x *CreateKycStatusRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *CreateKycStatusRequest) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type CreateKycStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KycId         string                 `protobuf:"bytes,1,opt,name=kyc_id,json=kycId,proto3" json:"kyc_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateKycStatusResponse) Reset() {
	*x = CreateKycStatusResponse{}
	mi := &file_brij_storage_v1_partner_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateKycStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateKycStatusResponse) ProtoMessage() {}

func (x *CreateKycStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_brij_storage_v1_partner_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateKycStatusResponse.ProtoReflect.Descriptor instead.
func (*CreateKycStatusResponse) Descriptor() ([]byte, []int) {
	return file_brij_storage_v1_partner_service_proto_rawDescGZIP(), []int{11}
}

func (x *CreateKycStatusResponse) GetKycId() string {
	if x != nil {
		return x.KycId
	}
	return ""
}

type UpdateKycStatusRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	KycId string                 `protobuf:"bytes,1,opt,name=kyc_id,json=kycId,proto3" json:"kyc_id,omitempty"`
	// KycEnvelope
	Payload       []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Signature     []byte `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateKycStatusRequest) Reset() {
	*x = UpdateKycStatusRequest{}
	mi := &file_brij_storage_v1_partner_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateKycStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateKycStatusRequest) ProtoMessage() {}

func (x *UpdateKycStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_brij_storage_v1_partner_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateKycStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateKycStatusRequest) Descriptor() ([]byte, []int) {
	return file_brij_storage_v1_partner_service_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateKycStatusRequest) GetKycId() string {
	if x != nil {
		return x.KycId
	}
	return ""
}

func (x *UpdateKycStatusRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *UpdateKycStatusRequest) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type UpdateKycStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateKycStatusResponse) Reset() {
	*x = UpdateKycStatusResponse{}
	mi := &file_brij_storage_v1_partner_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateKycStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateKycStatusResponse) ProtoMessage() {}

func (x *UpdateKycStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_brij_storage_v1_partner_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateKycStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateKycStatusResponse) Descriptor() ([]byte, []int) {
	return file_brij_storage_v1_partner_service_proto_rawDescGZIP(), []int{13}
}

var File_brij_storage_v1_partner_service_proto protoreflect.FileDescriptor

const file_brij_storage_v1_partner_service_proto_rawDesc = "" +
	"\n" +
	"%brij/storage/v1/partner/service.proto\x12\x17brij.storage.v1.partner\x1a&brij/storage/v1/common/user_data.proto\x1a,brij/storage/v1/common/validation_data.proto\"/\n" +
	"\x0eGetInfoRequest\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\tR\tpublicKey\"\x89\x01\n" +
	"\x0fGetInfoResponse\x120\n" +
	"\x14encrypted_secret_key\x18\x01 \x01(\tR\x12encryptedSecretKey\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\tR\tpublicKey\x12%\n" +
	"\x0ewallet_address\x18\x03 \x01(\tR\rwalletAddress\"c\n" +
	"\x12GetUserDataRequest\x12&\n" +
	"\x0fuser_public_key\x18\x01 \x01(\tR\ruserPublicKey\x12%\n" +
	"\x0einclude_values\x18\x02 \x01(\bR\rincludeValues\"\xaf\x01\n" +
	"\x13GetUserDataResponse\x12B\n" +
	"\tuser_data\x18\x01 \x03(\v2%.brij.storage.v1.common.UserDataFieldR\buserData\x12T\n" +
	"\x0fvalidation_data\x18\x02 \x03(\v2+.brij.storage.v1.common.ValidationDataFieldR\x0evalidationData\"R\n" +
	"\x18SetValidationDataRequest\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\"\x1b\n" +
	"\x19SetValidationDataResponse\":\n" +
	"\x1bRemoveValidationDataRequest\x12\x1b\n" +
	"\tdata_hash\x18\x01 \x01(\tR\bdataHash\"\x1e\n" +
	"\x1cRemoveValidationDataResponse\"\x89\x01\n" +
	"\x13GetKycStatusRequest\x12\x18\n" +
	"\acountry\x18\x01 \x01(\tR\acountry\x120\n" +
	"\x14validator_public_key\x18\x02 \x01(\tR\x12validatorPublicKey\x12&\n" +
	"\x0fuser_public_key\x18\x03 \x01(\tR\ruserPublicKey\"N\n" +
	"\x14GetKycStatusResponse\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\"P\n" +
	"\x16CreateKycStatusRequest\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\"0\n" +
	"\x17CreateKycStatusResponse\x12\x15\n" +
	"\x06kyc_id\x18\x01 \x01(\tR\x05kycId\"g\n" +
	"\x16UpdateKycStatusRequest\x12\x15\n" +
	"\x06kyc_id\x18\x01 \x01(\tR\x05kycId\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\fR\tsignature\"\x19\n" +
	"\x17UpdateKycStatusResponse2\xb3\x06\n" +
	"\x0ePartnerService\x12\\\n" +
	"\aGetInfo\x12'.brij.storage.v1.partner.GetInfoRequest\x1a(.brij.storage.v1.partner.GetInfoResponse\x12h\n" +
	"\vGetUserData\x12+.brij.storage.v1.partner.GetUserDataRequest\x1a,.brij.storage.v1.partner.GetUserDataResponse\x12z\n" +
	"\x11SetValidationData\x121.brij.storage.v1.partner.SetValidationDataRequest\x1a2.brij.storage.v1.partner.SetValidationDataResponse\x12\x83\x01\n" +
	"\x14RemoveValidationData\x124.brij.storage.v1.partner.RemoveValidationDataRequest\x1a5.brij.storage.v1.partner.RemoveValidationDataResponse\x12k\n" +
	"\fGetKycStatus\x12,.brij.storage.v1.partner.GetKycStatusRequest\x1a-.brij.storage.v1.partner.GetKycStatusResponse\x12t\n" +
	"\x0fCreateKycStatus\x12/.brij.storage.v1.partner.CreateKycStatusRequest\x1a0.brij.storage.v1.partner.CreateKycStatusResponse\x12t\n" +
	"\x0fUpdateKycStatus\x12/.brij.storage.v1.partner.UpdateKycStatusRequest\x1a0.brij.storage.v1.partner.UpdateKycStatusResponseB+Z)go.brij.fi/protos/brij/storage/v1/partnerb\x06proto3"

var (
	file_brij_storage_v1_partner_service_proto_rawDescOnce sync.Once
	file_brij_storage_v1_partner_service_proto_rawDescData []byte
)

func file_brij_storage_v1_partner_service_proto_rawDescGZIP() []byte {
	file_brij_storage_v1_partner_service_proto_rawDescOnce.Do(func() {
		file_brij_storage_v1_partner_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_brij_storage_v1_partner_service_proto_rawDesc), len(file_brij_storage_v1_partner_service_proto_rawDesc)))
	})
	return file_brij_storage_v1_partner_service_proto_rawDescData
}

var file_brij_storage_v1_partner_service_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_brij_storage_v1_partner_service_proto_goTypes = []any{
	(*GetInfoRequest)(nil),               // 0: brij.storage.v1.partner.GetInfoRequest
	(*GetInfoResponse)(nil),              // 1: brij.storage.v1.partner.GetInfoResponse
	(*GetUserDataRequest)(nil),           // 2: brij.storage.v1.partner.GetUserDataRequest
	(*GetUserDataResponse)(nil),          // 3: brij.storage.v1.partner.GetUserDataResponse
	(*SetValidationDataRequest)(nil),     // 4: brij.storage.v1.partner.SetValidationDataRequest
	(*SetValidationDataResponse)(nil),    // 5: brij.storage.v1.partner.SetValidationDataResponse
	(*RemoveValidationDataRequest)(nil),  // 6: brij.storage.v1.partner.RemoveValidationDataRequest
	(*RemoveValidationDataResponse)(nil), // 7: brij.storage.v1.partner.RemoveValidationDataResponse
	(*GetKycStatusRequest)(nil),          // 8: brij.storage.v1.partner.GetKycStatusRequest
	(*GetKycStatusResponse)(nil),         // 9: brij.storage.v1.partner.GetKycStatusResponse
	(*CreateKycStatusRequest)(nil),       // 10: brij.storage.v1.partner.CreateKycStatusRequest
	(*CreateKycStatusResponse)(nil),      // 11: brij.storage.v1.partner.CreateKycStatusResponse
	(*UpdateKycStatusRequest)(nil),       // 12: brij.storage.v1.partner.UpdateKycStatusRequest
	(*UpdateKycStatusResponse)(nil),      // 13: brij.storage.v1.partner.UpdateKycStatusResponse
	(*common.UserDataField)(nil),         // 14: brij.storage.v1.common.UserDataField
	(*common.ValidationDataField)(nil),   // 15: brij.storage.v1.common.ValidationDataField
}
var file_brij_storage_v1_partner_service_proto_depIdxs = []int32{
	14, // 0: brij.storage.v1.partner.GetUserDataResponse.user_data:type_name -> brij.storage.v1.common.UserDataField
	15, // 1: brij.storage.v1.partner.GetUserDataResponse.validation_data:type_name -> brij.storage.v1.common.ValidationDataField
	0,  // 2: brij.storage.v1.partner.PartnerService.GetInfo:input_type -> brij.storage.v1.partner.GetInfoRequest
	2,  // 3: brij.storage.v1.partner.PartnerService.GetUserData:input_type -> brij.storage.v1.partner.GetUserDataRequest
	4,  // 4: brij.storage.v1.partner.PartnerService.SetValidationData:input_type -> brij.storage.v1.partner.SetValidationDataRequest
	6,  // 5: brij.storage.v1.partner.PartnerService.RemoveValidationData:input_type -> brij.storage.v1.partner.RemoveValidationDataRequest
	8,  // 6: brij.storage.v1.partner.PartnerService.GetKycStatus:input_type -> brij.storage.v1.partner.GetKycStatusRequest
	10, // 7: brij.storage.v1.partner.PartnerService.CreateKycStatus:input_type -> brij.storage.v1.partner.CreateKycStatusRequest
	12, // 8: brij.storage.v1.partner.PartnerService.UpdateKycStatus:input_type -> brij.storage.v1.partner.UpdateKycStatusRequest
	1,  // 9: brij.storage.v1.partner.PartnerService.GetInfo:output_type -> brij.storage.v1.partner.GetInfoResponse
	3,  // 10: brij.storage.v1.partner.PartnerService.GetUserData:output_type -> brij.storage.v1.partner.GetUserDataResponse
	5,  // 11: brij.storage.v1.partner.PartnerService.SetValidationData:output_type -> brij.storage.v1.partner.SetValidationDataResponse
	7,  // 12: brij.storage.v1.partner.PartnerService.RemoveValidationData:output_type -> brij.storage.v1.partner.RemoveValidationDataResponse
	9,  // 13: brij.storage.v1.partner.PartnerService.GetKycStatus:output_type -> brij.storage.v1.partner.GetKycStatusResponse
	11, // 14: brij.storage.v1.partner.PartnerService.CreateKycStatus:output_type -> brij.storage.v1.partner.CreateKycStatusResponse
	13, // 15: brij.storage.v1.partner.PartnerService.UpdateKycStatus:output_type -> brij.storage.v1.partner.UpdateKycStatusResponse
	9,  // [9:16] is the sub-list for method output_type
	2,  // [2:9] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_brij_storage_v1_partner_service_proto_init() }
func file_brij_storage_v1_partner_service_proto_init() {
	if File_brij_storage_v1_partner_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_brij_storage_v1_partner_service_proto_rawDesc), len(file_brij_storage_v1_partner_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_brij_storage_v1_partner_service_proto_goTypes,
		DependencyIndexes: file_brij_storage_v1_partner_service_proto_depIdxs,
		MessageInfos:      file_brij_storage_v1_partner_service_proto_msgTypes,
	}.Build()
	File_brij_storage_v1_partner_service_proto = out.File
	file_brij_storage_v1_partner_service_proto_goTypes = nil
	file_brij_storage_v1_partner_service_proto_depIdxs = nil
}
