name: brij_protos_dart
description: A starting point for Dart libraries or applications.
version: 0.28.0

environment:
  sdk: ^3.7.2

dependencies:
  protobuf: ^4.1.0
  connectrpc: ^0.4.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
