// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: brij/storage/v1/wallet/service.proto

package walletconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	wallet "go.brij.fi/protos/brij/storage/v1/wallet"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// WalletServiceName is the fully-qualified name of the WalletService service.
	WalletServiceName = "brij.storage.v1.wallet.WalletService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// WalletServiceGetWalletProofProcedure is the fully-qualified name of the WalletService's
	// GetWalletProof RPC.
	WalletServiceGetWalletProofProcedure = "/brij.storage.v1.wallet.WalletService/GetWalletProof"
	// WalletServiceRestoreConnectionProcedure is the fully-qualified name of the WalletService's
	// RestoreConnection RPC.
	WalletServiceRestoreConnectionProcedure = "/brij.storage.v1.wallet.WalletService/RestoreConnection"
	// WalletServiceConnectWalletProcedure is the fully-qualified name of the WalletService's
	// ConnectWallet RPC.
	WalletServiceConnectWalletProcedure = "/brij.storage.v1.wallet.WalletService/ConnectWallet"
	// WalletServiceGetInfoProcedure is the fully-qualified name of the WalletService's GetInfo RPC.
	WalletServiceGetInfoProcedure = "/brij.storage.v1.wallet.WalletService/GetInfo"
	// WalletServiceGetPartnerInfoProcedure is the fully-qualified name of the WalletService's
	// GetPartnerInfo RPC.
	WalletServiceGetPartnerInfoProcedure = "/brij.storage.v1.wallet.WalletService/GetPartnerInfo"
	// WalletServiceGetGrantedAccessPartnersProcedure is the fully-qualified name of the WalletService's
	// GetGrantedAccessPartners RPC.
	WalletServiceGetGrantedAccessPartnersProcedure = "/brij.storage.v1.wallet.WalletService/GetGrantedAccessPartners"
	// WalletServiceGrantAccessProcedure is the fully-qualified name of the WalletService's GrantAccess
	// RPC.
	WalletServiceGrantAccessProcedure = "/brij.storage.v1.wallet.WalletService/GrantAccess"
	// WalletServiceSetUserDataProcedure is the fully-qualified name of the WalletService's SetUserData
	// RPC.
	WalletServiceSetUserDataProcedure = "/brij.storage.v1.wallet.WalletService/SetUserData"
	// WalletServiceRemoveUserDataProcedure is the fully-qualified name of the WalletService's
	// RemoveUserData RPC.
	WalletServiceRemoveUserDataProcedure = "/brij.storage.v1.wallet.WalletService/RemoveUserData"
	// WalletServiceRevokeAccessProcedure is the fully-qualified name of the WalletService's
	// RevokeAccess RPC.
	WalletServiceRevokeAccessProcedure = "/brij.storage.v1.wallet.WalletService/RevokeAccess"
	// WalletServiceRemoveAllUserDataProcedure is the fully-qualified name of the WalletService's
	// RemoveAllUserData RPC.
	WalletServiceRemoveAllUserDataProcedure = "/brij.storage.v1.wallet.WalletService/RemoveAllUserData"
	// WalletServiceGetUserDataProcedure is the fully-qualified name of the WalletService's GetUserData
	// RPC.
	WalletServiceGetUserDataProcedure = "/brij.storage.v1.wallet.WalletService/GetUserData"
	// WalletServiceCheckAccessProcedure is the fully-qualified name of the WalletService's CheckAccess
	// RPC.
	WalletServiceCheckAccessProcedure = "/brij.storage.v1.wallet.WalletService/CheckAccess"
	// WalletServiceGetKycStatusProcedure is the fully-qualified name of the WalletService's
	// GetKycStatus RPC.
	WalletServiceGetKycStatusProcedure = "/brij.storage.v1.wallet.WalletService/GetKycStatus"
)

// WalletServiceClient is a client for the brij.storage.v1.wallet.WalletService service.
type WalletServiceClient interface {
	GetWalletProof(context.Context, *connect.Request[wallet.GetWalletProofRequest]) (*connect.Response[wallet.GetWalletProofResponse], error)
	RestoreConnection(context.Context, *connect.Request[wallet.RestoreConnectionRequest]) (*connect.Response[wallet.RestoreConnectionResponse], error)
	ConnectWallet(context.Context, *connect.Request[wallet.ConnectWalletRequest]) (*connect.Response[wallet.ConnectWalletResponse], error)
	GetInfo(context.Context, *connect.Request[wallet.GetInfoRequest]) (*connect.Response[wallet.GetInfoResponse], error)
	GetPartnerInfo(context.Context, *connect.Request[wallet.GetPartnerInfoRequest]) (*connect.Response[wallet.GetPartnerInfoResponse], error)
	GetGrantedAccessPartners(context.Context, *connect.Request[wallet.GetGrantedAccessPartnersRequest]) (*connect.Response[wallet.GetGrantedAccessPartnersResponse], error)
	GrantAccess(context.Context, *connect.Request[wallet.GrantAccessRequest]) (*connect.Response[wallet.GrantAccessResponse], error)
	SetUserData(context.Context, *connect.Request[wallet.SetUserDataRequest]) (*connect.Response[wallet.SetUserDataResponse], error)
	RemoveUserData(context.Context, *connect.Request[wallet.RemoveUserDataRequest]) (*connect.Response[wallet.RemoveUserDataResponse], error)
	RevokeAccess(context.Context, *connect.Request[wallet.RevokeAccessRequest]) (*connect.Response[wallet.RevokeAccessResponse], error)
	RemoveAllUserData(context.Context, *connect.Request[wallet.RemoveAllUserDataRequest]) (*connect.Response[wallet.RemoveAllUserDataResponse], error)
	GetUserData(context.Context, *connect.Request[wallet.GetUserDataRequest]) (*connect.Response[wallet.GetUserDataResponse], error)
	CheckAccess(context.Context, *connect.Request[wallet.CheckAccessRequest]) (*connect.Response[wallet.CheckAccessResponse], error)
	GetKycStatus(context.Context, *connect.Request[wallet.GetKycStatusRequest]) (*connect.Response[wallet.GetKycStatusResponse], error)
}

// NewWalletServiceClient constructs a client for the brij.storage.v1.wallet.WalletService service.
// By default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped
// responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewWalletServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) WalletServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	walletServiceMethods := wallet.File_brij_storage_v1_wallet_service_proto.Services().ByName("WalletService").Methods()
	return &walletServiceClient{
		getWalletProof: connect.NewClient[wallet.GetWalletProofRequest, wallet.GetWalletProofResponse](
			httpClient,
			baseURL+WalletServiceGetWalletProofProcedure,
			connect.WithSchema(walletServiceMethods.ByName("GetWalletProof")),
			connect.WithClientOptions(opts...),
		),
		restoreConnection: connect.NewClient[wallet.RestoreConnectionRequest, wallet.RestoreConnectionResponse](
			httpClient,
			baseURL+WalletServiceRestoreConnectionProcedure,
			connect.WithSchema(walletServiceMethods.ByName("RestoreConnection")),
			connect.WithClientOptions(opts...),
		),
		connectWallet: connect.NewClient[wallet.ConnectWalletRequest, wallet.ConnectWalletResponse](
			httpClient,
			baseURL+WalletServiceConnectWalletProcedure,
			connect.WithSchema(walletServiceMethods.ByName("ConnectWallet")),
			connect.WithClientOptions(opts...),
		),
		getInfo: connect.NewClient[wallet.GetInfoRequest, wallet.GetInfoResponse](
			httpClient,
			baseURL+WalletServiceGetInfoProcedure,
			connect.WithSchema(walletServiceMethods.ByName("GetInfo")),
			connect.WithClientOptions(opts...),
		),
		getPartnerInfo: connect.NewClient[wallet.GetPartnerInfoRequest, wallet.GetPartnerInfoResponse](
			httpClient,
			baseURL+WalletServiceGetPartnerInfoProcedure,
			connect.WithSchema(walletServiceMethods.ByName("GetPartnerInfo")),
			connect.WithClientOptions(opts...),
		),
		getGrantedAccessPartners: connect.NewClient[wallet.GetGrantedAccessPartnersRequest, wallet.GetGrantedAccessPartnersResponse](
			httpClient,
			baseURL+WalletServiceGetGrantedAccessPartnersProcedure,
			connect.WithSchema(walletServiceMethods.ByName("GetGrantedAccessPartners")),
			connect.WithClientOptions(opts...),
		),
		grantAccess: connect.NewClient[wallet.GrantAccessRequest, wallet.GrantAccessResponse](
			httpClient,
			baseURL+WalletServiceGrantAccessProcedure,
			connect.WithSchema(walletServiceMethods.ByName("GrantAccess")),
			connect.WithClientOptions(opts...),
		),
		setUserData: connect.NewClient[wallet.SetUserDataRequest, wallet.SetUserDataResponse](
			httpClient,
			baseURL+WalletServiceSetUserDataProcedure,
			connect.WithSchema(walletServiceMethods.ByName("SetUserData")),
			connect.WithClientOptions(opts...),
		),
		removeUserData: connect.NewClient[wallet.RemoveUserDataRequest, wallet.RemoveUserDataResponse](
			httpClient,
			baseURL+WalletServiceRemoveUserDataProcedure,
			connect.WithSchema(walletServiceMethods.ByName("RemoveUserData")),
			connect.WithClientOptions(opts...),
		),
		revokeAccess: connect.NewClient[wallet.RevokeAccessRequest, wallet.RevokeAccessResponse](
			httpClient,
			baseURL+WalletServiceRevokeAccessProcedure,
			connect.WithSchema(walletServiceMethods.ByName("RevokeAccess")),
			connect.WithClientOptions(opts...),
		),
		removeAllUserData: connect.NewClient[wallet.RemoveAllUserDataRequest, wallet.RemoveAllUserDataResponse](
			httpClient,
			baseURL+WalletServiceRemoveAllUserDataProcedure,
			connect.WithSchema(walletServiceMethods.ByName("RemoveAllUserData")),
			connect.WithClientOptions(opts...),
		),
		getUserData: connect.NewClient[wallet.GetUserDataRequest, wallet.GetUserDataResponse](
			httpClient,
			baseURL+WalletServiceGetUserDataProcedure,
			connect.WithSchema(walletServiceMethods.ByName("GetUserData")),
			connect.WithClientOptions(opts...),
		),
		checkAccess: connect.NewClient[wallet.CheckAccessRequest, wallet.CheckAccessResponse](
			httpClient,
			baseURL+WalletServiceCheckAccessProcedure,
			connect.WithSchema(walletServiceMethods.ByName("CheckAccess")),
			connect.WithClientOptions(opts...),
		),
		getKycStatus: connect.NewClient[wallet.GetKycStatusRequest, wallet.GetKycStatusResponse](
			httpClient,
			baseURL+WalletServiceGetKycStatusProcedure,
			connect.WithSchema(walletServiceMethods.ByName("GetKycStatus")),
			connect.WithClientOptions(opts...),
		),
	}
}

// walletServiceClient implements WalletServiceClient.
type walletServiceClient struct {
	getWalletProof           *connect.Client[wallet.GetWalletProofRequest, wallet.GetWalletProofResponse]
	restoreConnection        *connect.Client[wallet.RestoreConnectionRequest, wallet.RestoreConnectionResponse]
	connectWallet            *connect.Client[wallet.ConnectWalletRequest, wallet.ConnectWalletResponse]
	getInfo                  *connect.Client[wallet.GetInfoRequest, wallet.GetInfoResponse]
	getPartnerInfo           *connect.Client[wallet.GetPartnerInfoRequest, wallet.GetPartnerInfoResponse]
	getGrantedAccessPartners *connect.Client[wallet.GetGrantedAccessPartnersRequest, wallet.GetGrantedAccessPartnersResponse]
	grantAccess              *connect.Client[wallet.GrantAccessRequest, wallet.GrantAccessResponse]
	setUserData              *connect.Client[wallet.SetUserDataRequest, wallet.SetUserDataResponse]
	removeUserData           *connect.Client[wallet.RemoveUserDataRequest, wallet.RemoveUserDataResponse]
	revokeAccess             *connect.Client[wallet.RevokeAccessRequest, wallet.RevokeAccessResponse]
	removeAllUserData        *connect.Client[wallet.RemoveAllUserDataRequest, wallet.RemoveAllUserDataResponse]
	getUserData              *connect.Client[wallet.GetUserDataRequest, wallet.GetUserDataResponse]
	checkAccess              *connect.Client[wallet.CheckAccessRequest, wallet.CheckAccessResponse]
	getKycStatus             *connect.Client[wallet.GetKycStatusRequest, wallet.GetKycStatusResponse]
}

// GetWalletProof calls brij.storage.v1.wallet.WalletService.GetWalletProof.
func (c *walletServiceClient) GetWalletProof(ctx context.Context, req *connect.Request[wallet.GetWalletProofRequest]) (*connect.Response[wallet.GetWalletProofResponse], error) {
	return c.getWalletProof.CallUnary(ctx, req)
}

// RestoreConnection calls brij.storage.v1.wallet.WalletService.RestoreConnection.
func (c *walletServiceClient) RestoreConnection(ctx context.Context, req *connect.Request[wallet.RestoreConnectionRequest]) (*connect.Response[wallet.RestoreConnectionResponse], error) {
	return c.restoreConnection.CallUnary(ctx, req)
}

// ConnectWallet calls brij.storage.v1.wallet.WalletService.ConnectWallet.
func (c *walletServiceClient) ConnectWallet(ctx context.Context, req *connect.Request[wallet.ConnectWalletRequest]) (*connect.Response[wallet.ConnectWalletResponse], error) {
	return c.connectWallet.CallUnary(ctx, req)
}

// GetInfo calls brij.storage.v1.wallet.WalletService.GetInfo.
func (c *walletServiceClient) GetInfo(ctx context.Context, req *connect.Request[wallet.GetInfoRequest]) (*connect.Response[wallet.GetInfoResponse], error) {
	return c.getInfo.CallUnary(ctx, req)
}

// GetPartnerInfo calls brij.storage.v1.wallet.WalletService.GetPartnerInfo.
func (c *walletServiceClient) GetPartnerInfo(ctx context.Context, req *connect.Request[wallet.GetPartnerInfoRequest]) (*connect.Response[wallet.GetPartnerInfoResponse], error) {
	return c.getPartnerInfo.CallUnary(ctx, req)
}

// GetGrantedAccessPartners calls brij.storage.v1.wallet.WalletService.GetGrantedAccessPartners.
func (c *walletServiceClient) GetGrantedAccessPartners(ctx context.Context, req *connect.Request[wallet.GetGrantedAccessPartnersRequest]) (*connect.Response[wallet.GetGrantedAccessPartnersResponse], error) {
	return c.getGrantedAccessPartners.CallUnary(ctx, req)
}

// GrantAccess calls brij.storage.v1.wallet.WalletService.GrantAccess.
func (c *walletServiceClient) GrantAccess(ctx context.Context, req *connect.Request[wallet.GrantAccessRequest]) (*connect.Response[wallet.GrantAccessResponse], error) {
	return c.grantAccess.CallUnary(ctx, req)
}

// SetUserData calls brij.storage.v1.wallet.WalletService.SetUserData.
func (c *walletServiceClient) SetUserData(ctx context.Context, req *connect.Request[wallet.SetUserDataRequest]) (*connect.Response[wallet.SetUserDataResponse], error) {
	return c.setUserData.CallUnary(ctx, req)
}

// RemoveUserData calls brij.storage.v1.wallet.WalletService.RemoveUserData.
func (c *walletServiceClient) RemoveUserData(ctx context.Context, req *connect.Request[wallet.RemoveUserDataRequest]) (*connect.Response[wallet.RemoveUserDataResponse], error) {
	return c.removeUserData.CallUnary(ctx, req)
}

// RevokeAccess calls brij.storage.v1.wallet.WalletService.RevokeAccess.
func (c *walletServiceClient) RevokeAccess(ctx context.Context, req *connect.Request[wallet.RevokeAccessRequest]) (*connect.Response[wallet.RevokeAccessResponse], error) {
	return c.revokeAccess.CallUnary(ctx, req)
}

// RemoveAllUserData calls brij.storage.v1.wallet.WalletService.RemoveAllUserData.
func (c *walletServiceClient) RemoveAllUserData(ctx context.Context, req *connect.Request[wallet.RemoveAllUserDataRequest]) (*connect.Response[wallet.RemoveAllUserDataResponse], error) {
	return c.removeAllUserData.CallUnary(ctx, req)
}

// GetUserData calls brij.storage.v1.wallet.WalletService.GetUserData.
func (c *walletServiceClient) GetUserData(ctx context.Context, req *connect.Request[wallet.GetUserDataRequest]) (*connect.Response[wallet.GetUserDataResponse], error) {
	return c.getUserData.CallUnary(ctx, req)
}

// CheckAccess calls brij.storage.v1.wallet.WalletService.CheckAccess.
func (c *walletServiceClient) CheckAccess(ctx context.Context, req *connect.Request[wallet.CheckAccessRequest]) (*connect.Response[wallet.CheckAccessResponse], error) {
	return c.checkAccess.CallUnary(ctx, req)
}

// GetKycStatus calls brij.storage.v1.wallet.WalletService.GetKycStatus.
func (c *walletServiceClient) GetKycStatus(ctx context.Context, req *connect.Request[wallet.GetKycStatusRequest]) (*connect.Response[wallet.GetKycStatusResponse], error) {
	return c.getKycStatus.CallUnary(ctx, req)
}

// WalletServiceHandler is an implementation of the brij.storage.v1.wallet.WalletService service.
type WalletServiceHandler interface {
	GetWalletProof(context.Context, *connect.Request[wallet.GetWalletProofRequest]) (*connect.Response[wallet.GetWalletProofResponse], error)
	RestoreConnection(context.Context, *connect.Request[wallet.RestoreConnectionRequest]) (*connect.Response[wallet.RestoreConnectionResponse], error)
	ConnectWallet(context.Context, *connect.Request[wallet.ConnectWalletRequest]) (*connect.Response[wallet.ConnectWalletResponse], error)
	GetInfo(context.Context, *connect.Request[wallet.GetInfoRequest]) (*connect.Response[wallet.GetInfoResponse], error)
	GetPartnerInfo(context.Context, *connect.Request[wallet.GetPartnerInfoRequest]) (*connect.Response[wallet.GetPartnerInfoResponse], error)
	GetGrantedAccessPartners(context.Context, *connect.Request[wallet.GetGrantedAccessPartnersRequest]) (*connect.Response[wallet.GetGrantedAccessPartnersResponse], error)
	GrantAccess(context.Context, *connect.Request[wallet.GrantAccessRequest]) (*connect.Response[wallet.GrantAccessResponse], error)
	SetUserData(context.Context, *connect.Request[wallet.SetUserDataRequest]) (*connect.Response[wallet.SetUserDataResponse], error)
	RemoveUserData(context.Context, *connect.Request[wallet.RemoveUserDataRequest]) (*connect.Response[wallet.RemoveUserDataResponse], error)
	RevokeAccess(context.Context, *connect.Request[wallet.RevokeAccessRequest]) (*connect.Response[wallet.RevokeAccessResponse], error)
	RemoveAllUserData(context.Context, *connect.Request[wallet.RemoveAllUserDataRequest]) (*connect.Response[wallet.RemoveAllUserDataResponse], error)
	GetUserData(context.Context, *connect.Request[wallet.GetUserDataRequest]) (*connect.Response[wallet.GetUserDataResponse], error)
	CheckAccess(context.Context, *connect.Request[wallet.CheckAccessRequest]) (*connect.Response[wallet.CheckAccessResponse], error)
	GetKycStatus(context.Context, *connect.Request[wallet.GetKycStatusRequest]) (*connect.Response[wallet.GetKycStatusResponse], error)
}

// NewWalletServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewWalletServiceHandler(svc WalletServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	walletServiceMethods := wallet.File_brij_storage_v1_wallet_service_proto.Services().ByName("WalletService").Methods()
	walletServiceGetWalletProofHandler := connect.NewUnaryHandler(
		WalletServiceGetWalletProofProcedure,
		svc.GetWalletProof,
		connect.WithSchema(walletServiceMethods.ByName("GetWalletProof")),
		connect.WithHandlerOptions(opts...),
	)
	walletServiceRestoreConnectionHandler := connect.NewUnaryHandler(
		WalletServiceRestoreConnectionProcedure,
		svc.RestoreConnection,
		connect.WithSchema(walletServiceMethods.ByName("RestoreConnection")),
		connect.WithHandlerOptions(opts...),
	)
	walletServiceConnectWalletHandler := connect.NewUnaryHandler(
		WalletServiceConnectWalletProcedure,
		svc.ConnectWallet,
		connect.WithSchema(walletServiceMethods.ByName("ConnectWallet")),
		connect.WithHandlerOptions(opts...),
	)
	walletServiceGetInfoHandler := connect.NewUnaryHandler(
		WalletServiceGetInfoProcedure,
		svc.GetInfo,
		connect.WithSchema(walletServiceMethods.ByName("GetInfo")),
		connect.WithHandlerOptions(opts...),
	)
	walletServiceGetPartnerInfoHandler := connect.NewUnaryHandler(
		WalletServiceGetPartnerInfoProcedure,
		svc.GetPartnerInfo,
		connect.WithSchema(walletServiceMethods.ByName("GetPartnerInfo")),
		connect.WithHandlerOptions(opts...),
	)
	walletServiceGetGrantedAccessPartnersHandler := connect.NewUnaryHandler(
		WalletServiceGetGrantedAccessPartnersProcedure,
		svc.GetGrantedAccessPartners,
		connect.WithSchema(walletServiceMethods.ByName("GetGrantedAccessPartners")),
		connect.WithHandlerOptions(opts...),
	)
	walletServiceGrantAccessHandler := connect.NewUnaryHandler(
		WalletServiceGrantAccessProcedure,
		svc.GrantAccess,
		connect.WithSchema(walletServiceMethods.ByName("GrantAccess")),
		connect.WithHandlerOptions(opts...),
	)
	walletServiceSetUserDataHandler := connect.NewUnaryHandler(
		WalletServiceSetUserDataProcedure,
		svc.SetUserData,
		connect.WithSchema(walletServiceMethods.ByName("SetUserData")),
		connect.WithHandlerOptions(opts...),
	)
	walletServiceRemoveUserDataHandler := connect.NewUnaryHandler(
		WalletServiceRemoveUserDataProcedure,
		svc.RemoveUserData,
		connect.WithSchema(walletServiceMethods.ByName("RemoveUserData")),
		connect.WithHandlerOptions(opts...),
	)
	walletServiceRevokeAccessHandler := connect.NewUnaryHandler(
		WalletServiceRevokeAccessProcedure,
		svc.RevokeAccess,
		connect.WithSchema(walletServiceMethods.ByName("RevokeAccess")),
		connect.WithHandlerOptions(opts...),
	)
	walletServiceRemoveAllUserDataHandler := connect.NewUnaryHandler(
		WalletServiceRemoveAllUserDataProcedure,
		svc.RemoveAllUserData,
		connect.WithSchema(walletServiceMethods.ByName("RemoveAllUserData")),
		connect.WithHandlerOptions(opts...),
	)
	walletServiceGetUserDataHandler := connect.NewUnaryHandler(
		WalletServiceGetUserDataProcedure,
		svc.GetUserData,
		connect.WithSchema(walletServiceMethods.ByName("GetUserData")),
		connect.WithHandlerOptions(opts...),
	)
	walletServiceCheckAccessHandler := connect.NewUnaryHandler(
		WalletServiceCheckAccessProcedure,
		svc.CheckAccess,
		connect.WithSchema(walletServiceMethods.ByName("CheckAccess")),
		connect.WithHandlerOptions(opts...),
	)
	walletServiceGetKycStatusHandler := connect.NewUnaryHandler(
		WalletServiceGetKycStatusProcedure,
		svc.GetKycStatus,
		connect.WithSchema(walletServiceMethods.ByName("GetKycStatus")),
		connect.WithHandlerOptions(opts...),
	)
	return "/brij.storage.v1.wallet.WalletService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case WalletServiceGetWalletProofProcedure:
			walletServiceGetWalletProofHandler.ServeHTTP(w, r)
		case WalletServiceRestoreConnectionProcedure:
			walletServiceRestoreConnectionHandler.ServeHTTP(w, r)
		case WalletServiceConnectWalletProcedure:
			walletServiceConnectWalletHandler.ServeHTTP(w, r)
		case WalletServiceGetInfoProcedure:
			walletServiceGetInfoHandler.ServeHTTP(w, r)
		case WalletServiceGetPartnerInfoProcedure:
			walletServiceGetPartnerInfoHandler.ServeHTTP(w, r)
		case WalletServiceGetGrantedAccessPartnersProcedure:
			walletServiceGetGrantedAccessPartnersHandler.ServeHTTP(w, r)
		case WalletServiceGrantAccessProcedure:
			walletServiceGrantAccessHandler.ServeHTTP(w, r)
		case WalletServiceSetUserDataProcedure:
			walletServiceSetUserDataHandler.ServeHTTP(w, r)
		case WalletServiceRemoveUserDataProcedure:
			walletServiceRemoveUserDataHandler.ServeHTTP(w, r)
		case WalletServiceRevokeAccessProcedure:
			walletServiceRevokeAccessHandler.ServeHTTP(w, r)
		case WalletServiceRemoveAllUserDataProcedure:
			walletServiceRemoveAllUserDataHandler.ServeHTTP(w, r)
		case WalletServiceGetUserDataProcedure:
			walletServiceGetUserDataHandler.ServeHTTP(w, r)
		case WalletServiceCheckAccessProcedure:
			walletServiceCheckAccessHandler.ServeHTTP(w, r)
		case WalletServiceGetKycStatusProcedure:
			walletServiceGetKycStatusHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedWalletServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedWalletServiceHandler struct{}

func (UnimplementedWalletServiceHandler) GetWalletProof(context.Context, *connect.Request[wallet.GetWalletProofRequest]) (*connect.Response[wallet.GetWalletProofResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("brij.storage.v1.wallet.WalletService.GetWalletProof is not implemented"))
}

func (UnimplementedWalletServiceHandler) RestoreConnection(context.Context, *connect.Request[wallet.RestoreConnectionRequest]) (*connect.Response[wallet.RestoreConnectionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("brij.storage.v1.wallet.WalletService.RestoreConnection is not implemented"))
}

func (UnimplementedWalletServiceHandler) ConnectWallet(context.Context, *connect.Request[wallet.ConnectWalletRequest]) (*connect.Response[wallet.ConnectWalletResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("brij.storage.v1.wallet.WalletService.ConnectWallet is not implemented"))
}

func (UnimplementedWalletServiceHandler) GetInfo(context.Context, *connect.Request[wallet.GetInfoRequest]) (*connect.Response[wallet.GetInfoResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("brij.storage.v1.wallet.WalletService.GetInfo is not implemented"))
}

func (UnimplementedWalletServiceHandler) GetPartnerInfo(context.Context, *connect.Request[wallet.GetPartnerInfoRequest]) (*connect.Response[wallet.GetPartnerInfoResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("brij.storage.v1.wallet.WalletService.GetPartnerInfo is not implemented"))
}

func (UnimplementedWalletServiceHandler) GetGrantedAccessPartners(context.Context, *connect.Request[wallet.GetGrantedAccessPartnersRequest]) (*connect.Response[wallet.GetGrantedAccessPartnersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("brij.storage.v1.wallet.WalletService.GetGrantedAccessPartners is not implemented"))
}

func (UnimplementedWalletServiceHandler) GrantAccess(context.Context, *connect.Request[wallet.GrantAccessRequest]) (*connect.Response[wallet.GrantAccessResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("brij.storage.v1.wallet.WalletService.GrantAccess is not implemented"))
}

func (UnimplementedWalletServiceHandler) SetUserData(context.Context, *connect.Request[wallet.SetUserDataRequest]) (*connect.Response[wallet.SetUserDataResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("brij.storage.v1.wallet.WalletService.SetUserData is not implemented"))
}

func (UnimplementedWalletServiceHandler) RemoveUserData(context.Context, *connect.Request[wallet.RemoveUserDataRequest]) (*connect.Response[wallet.RemoveUserDataResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("brij.storage.v1.wallet.WalletService.RemoveUserData is not implemented"))
}

func (UnimplementedWalletServiceHandler) RevokeAccess(context.Context, *connect.Request[wallet.RevokeAccessRequest]) (*connect.Response[wallet.RevokeAccessResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("brij.storage.v1.wallet.WalletService.RevokeAccess is not implemented"))
}

func (UnimplementedWalletServiceHandler) RemoveAllUserData(context.Context, *connect.Request[wallet.RemoveAllUserDataRequest]) (*connect.Response[wallet.RemoveAllUserDataResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("brij.storage.v1.wallet.WalletService.RemoveAllUserData is not implemented"))
}

func (UnimplementedWalletServiceHandler) GetUserData(context.Context, *connect.Request[wallet.GetUserDataRequest]) (*connect.Response[wallet.GetUserDataResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("brij.storage.v1.wallet.WalletService.GetUserData is not implemented"))
}

func (UnimplementedWalletServiceHandler) CheckAccess(context.Context, *connect.Request[wallet.CheckAccessRequest]) (*connect.Response[wallet.CheckAccessResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("brij.storage.v1.wallet.WalletService.CheckAccess is not implemented"))
}

func (UnimplementedWalletServiceHandler) GetKycStatus(context.Context, *connect.Request[wallet.GetKycStatusRequest]) (*connect.Response[wallet.GetKycStatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("brij.storage.v1.wallet.WalletService.GetKycStatus is not implemented"))
}
