// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: brij/orders/manage/v1/service.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NotifyPartnerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	WebhookUrl    string                 `protobuf:"bytes,2,opt,name=webhook_url,json=webhookUrl,proto3" json:"webhook_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyPartnerRequest) Reset() {
	*x = NotifyPartnerRequest{}
	mi := &file_brij_orders_manage_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyPartnerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyPartnerRequest) ProtoMessage() {}

func (x *NotifyPartnerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_brij_orders_manage_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyPartnerRequest.ProtoReflect.Descriptor instead.
func (*NotifyPartnerRequest) Descriptor() ([]byte, []int) {
	return file_brij_orders_manage_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *NotifyPartnerRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *NotifyPartnerRequest) GetWebhookUrl() string {
	if x != nil {
		return x.WebhookUrl
	}
	return ""
}

type NotifyPartnerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyPartnerResponse) Reset() {
	*x = NotifyPartnerResponse{}
	mi := &file_brij_orders_manage_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyPartnerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyPartnerResponse) ProtoMessage() {}

func (x *NotifyPartnerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_brij_orders_manage_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyPartnerResponse.ProtoReflect.Descriptor instead.
func (*NotifyPartnerResponse) Descriptor() ([]byte, []int) {
	return file_brij_orders_manage_v1_service_proto_rawDescGZIP(), []int{1}
}

type CheckStaleOrdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckStaleOrdersRequest) Reset() {
	*x = CheckStaleOrdersRequest{}
	mi := &file_brij_orders_manage_v1_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckStaleOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckStaleOrdersRequest) ProtoMessage() {}

func (x *CheckStaleOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_brij_orders_manage_v1_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckStaleOrdersRequest.ProtoReflect.Descriptor instead.
func (*CheckStaleOrdersRequest) Descriptor() ([]byte, []int) {
	return file_brij_orders_manage_v1_service_proto_rawDescGZIP(), []int{2}
}

type CheckStaleOrdersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckStaleOrdersResponse) Reset() {
	*x = CheckStaleOrdersResponse{}
	mi := &file_brij_orders_manage_v1_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckStaleOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckStaleOrdersResponse) ProtoMessage() {}

func (x *CheckStaleOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_brij_orders_manage_v1_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckStaleOrdersResponse.ProtoReflect.Descriptor instead.
func (*CheckStaleOrdersResponse) Descriptor() ([]byte, []int) {
	return file_brij_orders_manage_v1_service_proto_rawDescGZIP(), []int{3}
}

var File_brij_orders_manage_v1_service_proto protoreflect.FileDescriptor

const file_brij_orders_manage_v1_service_proto_rawDesc = "" +
	"\n" +
	"#brij/orders/manage/v1/service.proto\x12\x15brij.orders.manage.v1\"R\n" +
	"\x14NotifyPartnerRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x1f\n" +
	"\vwebhook_url\x18\x02 \x01(\tR\n" +
	"webhookUrl\"\x17\n" +
	"\x15NotifyPartnerResponse\"\x19\n" +
	"\x17CheckStaleOrdersRequest\"\x1a\n" +
	"\x18CheckStaleOrdersResponse2\xf0\x01\n" +
	"\rManageService\x12j\n" +
	"\rNotifyPartner\x12+.brij.orders.manage.v1.NotifyPartnerRequest\x1a,.brij.orders.manage.v1.NotifyPartnerResponse\x12s\n" +
	"\x10CheckStaleOrders\x12..brij.orders.manage.v1.CheckStaleOrdersRequest\x1a/.brij.orders.manage.v1.CheckStaleOrdersResponseB)Z'go.brij.fi/protos/brij/orders/manage/v1b\x06proto3"

var (
	file_brij_orders_manage_v1_service_proto_rawDescOnce sync.Once
	file_brij_orders_manage_v1_service_proto_rawDescData []byte
)

func file_brij_orders_manage_v1_service_proto_rawDescGZIP() []byte {
	file_brij_orders_manage_v1_service_proto_rawDescOnce.Do(func() {
		file_brij_orders_manage_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_brij_orders_manage_v1_service_proto_rawDesc), len(file_brij_orders_manage_v1_service_proto_rawDesc)))
	})
	return file_brij_orders_manage_v1_service_proto_rawDescData
}

var file_brij_orders_manage_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_brij_orders_manage_v1_service_proto_goTypes = []any{
	(*NotifyPartnerRequest)(nil),     // 0: brij.orders.manage.v1.NotifyPartnerRequest
	(*NotifyPartnerResponse)(nil),    // 1: brij.orders.manage.v1.NotifyPartnerResponse
	(*CheckStaleOrdersRequest)(nil),  // 2: brij.orders.manage.v1.CheckStaleOrdersRequest
	(*CheckStaleOrdersResponse)(nil), // 3: brij.orders.manage.v1.CheckStaleOrdersResponse
}
var file_brij_orders_manage_v1_service_proto_depIdxs = []int32{
	0, // 0: brij.orders.manage.v1.ManageService.NotifyPartner:input_type -> brij.orders.manage.v1.NotifyPartnerRequest
	2, // 1: brij.orders.manage.v1.ManageService.CheckStaleOrders:input_type -> brij.orders.manage.v1.CheckStaleOrdersRequest
	1, // 2: brij.orders.manage.v1.ManageService.NotifyPartner:output_type -> brij.orders.manage.v1.NotifyPartnerResponse
	3, // 3: brij.orders.manage.v1.ManageService.CheckStaleOrders:output_type -> brij.orders.manage.v1.CheckStaleOrdersResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_brij_orders_manage_v1_service_proto_init() }
func file_brij_orders_manage_v1_service_proto_init() {
	if File_brij_orders_manage_v1_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_brij_orders_manage_v1_service_proto_rawDesc), len(file_brij_orders_manage_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_brij_orders_manage_v1_service_proto_goTypes,
		DependencyIndexes: file_brij_orders_manage_v1_service_proto_depIdxs,
		MessageInfos:      file_brij_orders_manage_v1_service_proto_msgTypes,
	}.Build()
	File_brij_orders_manage_v1_service_proto = out.File
	file_brij_orders_manage_v1_service_proto_goTypes = nil
	file_brij_orders_manage_v1_service_proto_depIdxs = nil
}
