// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: brij/storage/v1/common/user_data_field.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserDataField struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type           DataType               `protobuf:"varint,2,opt,name=type,proto3,enum=brij.storage.v1.common.DataType" json:"type,omitempty"`
	EncryptedValue []byte                 `protobuf:"bytes,3,opt,name=encrypted_value,json=encryptedValue,proto3" json:"encrypted_value,omitempty"`
	Hash           string                 `protobuf:"bytes,4,opt,name=hash,proto3" json:"hash,omitempty"`
	Signature      string                 `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UserDataField) Reset() {
	*x = UserDataField{}
	mi := &file_brij_storage_v1_common_user_data_field_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserDataField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDataField) ProtoMessage() {}

func (x *UserDataField) ProtoReflect() protoreflect.Message {
	mi := &file_brij_storage_v1_common_user_data_field_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDataField.ProtoReflect.Descriptor instead.
func (*UserDataField) Descriptor() ([]byte, []int) {
	return file_brij_storage_v1_common_user_data_field_proto_rawDescGZIP(), []int{0}
}

func (x *UserDataField) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserDataField) GetType() DataType {
	if x != nil {
		return x.Type
	}
	return DataType_DATA_TYPE_UNSPECIFIED
}

func (x *UserDataField) GetEncryptedValue() []byte {
	if x != nil {
		return x.EncryptedValue
	}
	return nil
}

func (x *UserDataField) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *UserDataField) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *UserDataField) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_brij_storage_v1_common_user_data_field_proto protoreflect.FileDescriptor

const file_brij_storage_v1_common_user_data_field_proto_rawDesc = "" +
	"\n" +
	",brij/storage/v1/common/user_data_field.proto\x12\x16brij.storage.v1.common\x1a!brij/storage/v1/common/data.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xeb\x01\n" +
	"\rUserDataField\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x124\n" +
	"\x04type\x18\x02 \x01(\x0e2 .brij.storage.v1.common.DataTypeR\x04type\x12'\n" +
	"\x0fencrypted_value\x18\x03 \x01(\fR\x0eencryptedValue\x12\x12\n" +
	"\x04hash\x18\x04 \x01(\tR\x04hash\x12\x1c\n" +
	"\tsignature\x18\x05 \x01(\tR\tsignature\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAtB*Z(go.brij.fi/protos/brij/storage/v1/commonb\x06proto3"

var (
	file_brij_storage_v1_common_user_data_field_proto_rawDescOnce sync.Once
	file_brij_storage_v1_common_user_data_field_proto_rawDescData []byte
)

func file_brij_storage_v1_common_user_data_field_proto_rawDescGZIP() []byte {
	file_brij_storage_v1_common_user_data_field_proto_rawDescOnce.Do(func() {
		file_brij_storage_v1_common_user_data_field_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_brij_storage_v1_common_user_data_field_proto_rawDesc), len(file_brij_storage_v1_common_user_data_field_proto_rawDesc)))
	})
	return file_brij_storage_v1_common_user_data_field_proto_rawDescData
}

var file_brij_storage_v1_common_user_data_field_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_brij_storage_v1_common_user_data_field_proto_goTypes = []any{
	(*UserDataField)(nil),         // 0: brij.storage.v1.common.UserDataField
	(DataType)(0),                 // 1: brij.storage.v1.common.DataType
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_brij_storage_v1_common_user_data_field_proto_depIdxs = []int32{
	1, // 0: brij.storage.v1.common.UserDataField.type:type_name -> brij.storage.v1.common.DataType
	2, // 1: brij.storage.v1.common.UserDataField.created_at:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_brij_storage_v1_common_user_data_field_proto_init() }
func file_brij_storage_v1_common_user_data_field_proto_init() {
	if File_brij_storage_v1_common_user_data_field_proto != nil {
		return
	}
	file_brij_storage_v1_common_data_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_brij_storage_v1_common_user_data_field_proto_rawDesc), len(file_brij_storage_v1_common_user_data_field_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_brij_storage_v1_common_user_data_field_proto_goTypes,
		DependencyIndexes: file_brij_storage_v1_common_user_data_field_proto_depIdxs,
		MessageInfos:      file_brij_storage_v1_common_user_data_field_proto_msgTypes,
	}.Build()
	File_brij_storage_v1_common_user_data_field_proto = out.File
	file_brij_storage_v1_common_user_data_field_proto_goTypes = nil
	file_brij_storage_v1_common_user_data_field_proto_depIdxs = nil
}
