// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: brij/storage/v1/common/validation_status.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ValidationStatus int32

const (
	ValidationStatus_VALIDATION_STATUS_UNSPECIFIED ValidationStatus = 0
	ValidationStatus_VALIDATION_STATUS_PENDING     ValidationStatus = 1
	ValidationStatus_VALIDATION_STATUS_APPROVED    ValidationStatus = 2
	ValidationStatus_VALIDATION_STATUS_REJECTED    ValidationStatus = 3
)

// Enum value maps for ValidationStatus.
var (
	ValidationStatus_name = map[int32]string{
		0: "VALIDATION_STATUS_UNSPECIFIED",
		1: "VALIDATION_STATUS_PENDING",
		2: "VALIDATION_STATUS_APPROVED",
		3: "VALIDATION_STATUS_REJECTED",
	}
	ValidationStatus_value = map[string]int32{
		"VALIDATION_STATUS_UNSPECIFIED": 0,
		"VALIDATION_STATUS_PENDING":     1,
		"VALIDATION_STATUS_APPROVED":    2,
		"VALIDATION_STATUS_REJECTED":    3,
	}
)

func (x ValidationStatus) Enum() *ValidationStatus {
	p := new(ValidationStatus)
	*p = x
	return p
}

func (x ValidationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ValidationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_brij_storage_v1_common_validation_status_proto_enumTypes[0].Descriptor()
}

func (ValidationStatus) Type() protoreflect.EnumType {
	return &file_brij_storage_v1_common_validation_status_proto_enumTypes[0]
}

func (x ValidationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ValidationStatus.Descriptor instead.
func (ValidationStatus) EnumDescriptor() ([]byte, []int) {
	return file_brij_storage_v1_common_validation_status_proto_rawDescGZIP(), []int{0}
}

var File_brij_storage_v1_common_validation_status_proto protoreflect.FileDescriptor

var file_brij_storage_v1_common_validation_status_proto_rawDesc = []byte{
	0x0a, 0x2e, 0x62, 0x72, 0x69, 0x6a, 0x2f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2f, 0x76,
	0x31, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x16, 0x62, 0x72, 0x69, 0x6a, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x76,
	0x31, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2a, 0x94, 0x01, 0x0a, 0x10, 0x56, 0x61, 0x6c,
	0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x21, 0x0a,
	0x1d, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x53, 0x54, 0x41, 0x54,
	0x55, 0x53, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00,
	0x12, 0x1d, 0x0a, 0x19, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x53,
	0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x50, 0x45, 0x4e, 0x44, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12,
	0x1e, 0x0a, 0x1a, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x53, 0x54,
	0x41, 0x54, 0x55, 0x53, 0x5f, 0x41, 0x50, 0x50, 0x52, 0x4f, 0x56, 0x45, 0x44, 0x10, 0x02, 0x12,
	0x1e, 0x0a, 0x1a, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x53, 0x54,
	0x41, 0x54, 0x55, 0x53, 0x5f, 0x52, 0x45, 0x4a, 0x45, 0x43, 0x54, 0x45, 0x44, 0x10, 0x03, 0x42,
	0x2a, 0x5a, 0x28, 0x67, 0x6f, 0x2e, 0x62, 0x72, 0x69, 0x6a, 0x2e, 0x66, 0x69, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x62, 0x72, 0x69, 0x6a, 0x2f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67,
	0x65, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_brij_storage_v1_common_validation_status_proto_rawDescOnce sync.Once
	file_brij_storage_v1_common_validation_status_proto_rawDescData = file_brij_storage_v1_common_validation_status_proto_rawDesc
)

func file_brij_storage_v1_common_validation_status_proto_rawDescGZIP() []byte {
	file_brij_storage_v1_common_validation_status_proto_rawDescOnce.Do(func() {
		file_brij_storage_v1_common_validation_status_proto_rawDescData = protoimpl.X.CompressGZIP(file_brij_storage_v1_common_validation_status_proto_rawDescData)
	})
	return file_brij_storage_v1_common_validation_status_proto_rawDescData
}

var file_brij_storage_v1_common_validation_status_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_brij_storage_v1_common_validation_status_proto_goTypes = []any{
	(ValidationStatus)(0), // 0: brij.storage.v1.common.ValidationStatus
}
var file_brij_storage_v1_common_validation_status_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_brij_storage_v1_common_validation_status_proto_init() }
func file_brij_storage_v1_common_validation_status_proto_init() {
	if File_brij_storage_v1_common_validation_status_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_brij_storage_v1_common_validation_status_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_brij_storage_v1_common_validation_status_proto_goTypes,
		DependencyIndexes: file_brij_storage_v1_common_validation_status_proto_depIdxs,
		EnumInfos:         file_brij_storage_v1_common_validation_status_proto_enumTypes,
	}.Build()
	File_brij_storage_v1_common_validation_status_proto = out.File
	file_brij_storage_v1_common_validation_status_proto_rawDesc = nil
	file_brij_storage_v1_common_validation_status_proto_goTypes = nil
	file_brij_storage_v1_common_validation_status_proto_depIdxs = nil
}
