name: Check PR

on:
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  check-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: task build

      - name: Test
        run: task test
